import { GRADES, type GradeId } from "./grades";
import colorPhotos from "@/data/color-photos.json";

export type Brand = "Apple" | "Samsung";
export type DeviceType = "phone" | "tablet";
export type CameraLayout =
  | "triple"
  | "dual"
  | "single"
  | "vertical"
  | "grid"
  | "bar"
  | "circular";

export type ColorFamily =
  | "Black"
  | "Gray"
  | "Silver"
  | "White"
  | "Gold"
  | "Blue"
  | "Green"
  | "Purple"
  | "Pink"
  | "Red"
  | "Orange"
  | "Yellow"
  | "Titanium";

export interface Colorway {
  name: string;
  hex: string;
  accent: string;
  family: ColorFamily;
  /** per-color product photo (wired from public/photos via color-photos.json) */
  image?: string;
}

export interface StorageOption {
  gb: number;
  price: number;
  original: number;
  wholesale: number;
}

export interface Device {
  id: string;
  slug: string;
  brand: Brand;
  type: DeviceType;
  name: string;
  line: string;
  releaseYear: number;
  chip: string;
  screen: number;
  ram: number;
  colors: Colorway[];
  storage: StorageOption[];
  grade: GradeId;
  batteryHealth: number;
  /** manufacturer model number(s) for the US variant, e.g. "A2649" / "SM-S911U" */
  modelNumbers?: string;
  cameraLayout: CameraLayout;
  fiveG: boolean;
  cellular?: boolean;
  rating: number;
  reviews: number;
  stock: number;
  popular?: boolean;
  badge?: string;
  features: string[];
  highlights: string[];
  image?: string;
}

export const BRANDS: Brand[] = ["Apple", "Samsung"];
export const DEVICE_TYPES: DeviceType[] = ["phone", "tablet"];
export const COLOR_FAMILIES: ColorFamily[] = [
  "Black",
  "Gray",
  "Silver",
  "White",
  "Titanium",
  "Gold",
  "Blue",
  "Green",
  "Purple",
  "Pink",
  "Red",
  "Orange",
  "Yellow",
];

export const DEVICES: Device[] = [
  {
    id: "ipxr",
    slug: "iphone-xr",
    brand: "Apple",
    type: "phone",
    name: "iPhone XR",
    line: "iPhone XR",
    releaseYear: 2018,
    modelNumbers: "A1984",
    chip: "A12 Bionic",
    screen: 6.1,
    ram: 3,
    colors: [
      { name: "Black", hex: "#1f2123", accent: "#3a3c3f", family: "Black" },
      { name: "Blue", hex: "#a4d4e8", accent: "#7db0c8", family: "Blue" },
      { name: "Coral", hex: "#fa7d6b", accent: "#e0594a", family: "Pink" },
      { name: "Yellow", hex: "#f6d96b", accent: "#dcbf52", family: "Yellow" },
      { name: "White", hex: "#f4f4f2", accent: "#d6d6d3", family: "White" },
      { name: "Red", hex: "#c5283d", accent: "#97202f", family: "Red" },
    ],
    storage: [
      { gb: 64, price: 169, original: 749, wholesale: 154 },
      { gb: 128, price: 199, original: 799, wholesale: 181 },
      { gb: 256, price: 239, original: 899, wholesale: 218 },
    ],
    grade: "good",
    batteryHealth: 85,
    cameraLayout: "single",
    fiveG: false,
    rating: 4.4,
    reviews: 83,
    stock: 0,
    features: ["12MP single", "Liquid Retina LCD", "A12 Bionic", "Face ID"],
    highlights: [
      "The value entry into Face ID iPhones",
      "All-day battery in a colorful body",
      "Liquid Retina display with True Tone",
    ],
  },
  {
    id: "ip11",
    slug: "iphone-11",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11",
    line: "iPhone 11",
    releaseYear: 2019,
    modelNumbers: "A2111",
    chip: "A13 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Black", hex: "#1d1d1f", accent: "#3a3a3c", family: "Black" },
      { name: "White", hex: "#f5f5f0", accent: "#d8d8d2", family: "White" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
      { name: "Yellow", hex: "#f6d860", accent: "#d8b945", family: "Yellow" },
      { name: "Purple", hex: "#d6c8e8", accent: "#b3a3cc", family: "Purple" },
      { name: "Green", hex: "#c9e3c5", accent: "#a3c79e", family: "Green" },
    ],
    storage: [
      { gb: 64, price: 219, original: 699, wholesale: 199 },
      { gb: 128, price: 259, original: 749, wholesale: 236 },
      { gb: 256, price: 299, original: 849, wholesale: 272 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "dual",
    fiveG: false,
    rating: 4.6,
    reviews: 130,
    stock: 142,
    popular: true,
    badge: "Best seller",
    features: ["Dual 12MP", "Liquid Retina", "A13 Bionic", "Face ID"],
    highlights: [
      "Unbeatable everyday value pick",
      "All-day battery and Night mode photos",
      "Six fun colors to choose from",
    ],
  },
  {
    id: "ip11pro",
    slug: "iphone-11-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11 Pro",
    line: "iPhone 11",
    releaseYear: 2019,
    modelNumbers: "A2160",
    chip: "A13 Bionic",
    screen: 5.8,
    ram: 4,
    colors: [
      { name: "Midnight Green", hex: "#4e5851", accent: "#3a423d", family: "Green" },
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#f7e8cf", accent: "#e0c9a3", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 269, original: 999, wholesale: 245 },
      { gb: 256, price: 319, original: 1149, wholesale: 290 },
      { gb: 512, price: 369, original: 1349, wholesale: 336 },
    ],
    grade: "good",
    batteryHealth: 85,
    cameraLayout: "triple",
    fiveG: false,
    rating: 4.6,
    reviews: 76,
    stock: 78,
    features: ["Triple 12MP", "Super Retina XDR", "A13 Bionic", "Night mode"],
    highlights: [
      "First Pro triple-camera system",
      "Gorgeous OLED Super Retina XDR display",
      "Premium stainless steel frame",
    ],
  },
  {
    id: "ip11pm",
    slug: "iphone-11-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11 Pro Max",
    line: "iPhone 11",
    releaseYear: 2019,
    modelNumbers: "A2161",
    chip: "A13 Bionic",
    screen: 6.5,
    ram: 4,
    colors: [
      { name: "Midnight Green", hex: "#4e5851", accent: "#3a423d", family: "Green" },
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#f7e8cf", accent: "#e0c9a3", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 309, original: 1099, wholesale: 281 },
      { gb: 256, price: 369, original: 1249, wholesale: 336 },
      { gb: 512, price: 429, original: 1449, wholesale: 390 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "triple",
    fiveG: false,
    rating: 4.7,
    reviews: 98,
    stock: 64,
    features: ["Triple 12MP", '6.5" OLED', "A13 Bionic", "Best battery"],
    highlights: [
      "Largest, brightest display of its era",
      "Exceptional battery longevity",
      "Pro triple-camera versatility",
    ],
  },
  {
    id: "ip12mini",
    slug: "iphone-12-mini",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 mini",
    line: "iPhone 12",
    releaseYear: 2020,
    modelNumbers: "A2176",
    chip: "A14 Bionic",
    screen: 5.4,
    ram: 4,
    colors: [
      { name: "Black", hex: "#26282b", accent: "#3f4145", family: "Black" },
      { name: "White", hex: "#f6f6f1", accent: "#d9d9d3", family: "White" },
      { name: "Red", hex: "#c1283a", accent: "#931e2c", family: "Red" },
      { name: "Green", hex: "#a7c3a0", accent: "#84a07d", family: "Green" },
      { name: "Blue", hex: "#2b4a73", accent: "#436a99", family: "Blue" },
      { name: "Purple", hex: "#b7b4e3", accent: "#9692c4", family: "Purple" },
    ],
    storage: [
      { gb: 64, price: 249, original: 699, wholesale: 227 },
      { gb: 128, price: 289, original: 749, wholesale: 263 },
      { gb: 256, price: 339, original: 849, wholesale: 308 },
    ],
    grade: "good",
    batteryHealth: 84,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.5,
    reviews: 40,
    stock: 8,
    features: ["Dual 12MP", '5.4" OLED', "A14 Bionic", "5G"],
    highlights: [
      "The most compact 5G iPhone",
      "Full flagship power in one hand",
      "Ceramic Shield front protection",
    ],
  },
  {
    id: "ip12",
    slug: "iphone-12",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12",
    line: "iPhone 12",
    releaseYear: 2020,
    modelNumbers: "A2172",
    chip: "A14 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Black", hex: "#26282b", accent: "#3f4145", family: "Black" },
      { name: "White", hex: "#f6f6f1", accent: "#d9d9d3", family: "White" },
      { name: "Red", hex: "#c1283a", accent: "#931e2c", family: "Red" },
      { name: "Green", hex: "#a7c3a0", accent: "#84a07d", family: "Green" },
      { name: "Blue", hex: "#2b4a73", accent: "#436a99", family: "Blue" },
      { name: "Purple", hex: "#b9b6e5", accent: "#9693c4", family: "Purple" },
    ],
    storage: [
      { gb: 64, price: 299, original: 799, wholesale: 272 },
      { gb: 128, price: 339, original: 849, wholesale: 308 },
      { gb: 256, price: 389, original: 949, wholesale: 354 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 112,
    stock: 118,
    popular: true,
    badge: "Great value",
    features: ["Dual 12MP", "Super Retina XDR", "A14 Bionic", "5G"],
    highlights: [
      "The 5G workhorse that still delivers",
      "Ceramic Shield and OLED display",
      "Compact, flat-edge design",
    ],
  },
  {
    id: "ip12pro",
    slug: "iphone-12-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 Pro",
    line: "iPhone 12",
    releaseYear: 2020,
    modelNumbers: "A2341",
    chip: "A14 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Pacific Blue", hex: "#42637e", accent: "#314b60", family: "Blue" },
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
    ],
    storage: [
      { gb: 128, price: 379, original: 999, wholesale: 345 },
      { gb: 256, price: 439, original: 1099, wholesale: 400 },
      { gb: 512, price: 509, original: 1299, wholesale: 463 },
    ],
    grade: "excellent",
    batteryHealth: 87,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.7,
    reviews: 58,
    stock: 57,
    features: ["Triple 12MP", "LiDAR scanner", "Super Retina XDR", "5G"],
    highlights: [
      "LiDAR for fast low-light focus",
      "ProRAW photography support",
      "Stainless steel Pro design",
    ],
  },
  {
    id: "ip12pm",
    slug: "iphone-12-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 Pro Max",
    line: "iPhone 12",
    releaseYear: 2020,
    modelNumbers: "A2342",
    chip: "A14 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Pacific Blue", hex: "#42637e", accent: "#314b60", family: "Blue" },
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
    ],
    storage: [
      { gb: 128, price: 429, original: 1099, wholesale: 390 },
      { gb: 256, price: 489, original: 1199, wholesale: 445 },
      { gb: 512, price: 559, original: 1399, wholesale: 509 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 88,
    stock: 49,
    popular: true,
    features: ["Triple 12MP", "Sensor-shift OIS", '6.7" OLED', "LiDAR"],
    highlights: [
      "Largest sensor of the 12 lineup",
      "Sensor-shift stabilization for sharp shots",
      "Expansive 6.7-inch OLED canvas",
    ],
  },
  {
    id: "ip13mini",
    slug: "iphone-13-mini",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 mini",
    line: "iPhone 13",
    releaseYear: 2021,
    modelNumbers: "A2481",
    chip: "A15 Bionic",
    screen: 5.4,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#37618e", accent: "#5b85b3", family: "Blue" },
      { name: "Pink", hex: "#f7d6d9", accent: "#e6b3bb", family: "Pink" },
      { name: "Green", hex: "#3a4a3f", accent: "#5d7565", family: "Green" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 339, original: 699, wholesale: 308 },
      { gb: 256, price: 399, original: 799, wholesale: 363 },
      { gb: 512, price: 479, original: 999, wholesale: 434 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 33,
    stock: 11,
    features: ["Dual 12MP", "Cinematic mode", '5.4" OLED', "5G"],
    highlights: [
      "Big-phone performance, small footprint",
      "Improved battery over 12 mini",
      "Cinematic mode video built in",
    ],
  },
  {
    id: "ip13",
    slug: "iphone-13",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13",
    line: "iPhone 13",
    releaseYear: 2021,
    modelNumbers: "A2482",
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#37618e", accent: "#5b85b3", family: "Blue" },
      { name: "Pink", hex: "#f7d6d9", accent: "#e6b3bb", family: "Pink" },
      { name: "Green", hex: "#3a4a3f", accent: "#5d7565", family: "Green" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 389, original: 699, wholesale: 349 },
      { gb: 256, price: 449, original: 799, wholesale: 405 },
      { gb: 512, price: 529, original: 999, wholesale: 479 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 90,
    stock: 96,
    popular: true,
    features: ["Dual 12MP", "Cinematic mode", "Super Retina XDR", "Face ID"],
    highlights: [
      "The value champion of the lineup",
      "Cinematic mode for depth-of-field video",
      "Still receiving the latest iOS updates",
    ],
  },
  {
    id: "ip13pro",
    slug: "iphone-13-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 Pro",
    line: "iPhone 13",
    releaseYear: 2021,
    modelNumbers: "A2483",
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Sierra Blue", hex: "#a7c5e3", accent: "#7fa3c4", family: "Blue" },
      { name: "Alpine Green", hex: "#535f4f", accent: "#3e4a3b", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 489, original: 999, wholesale: 445 },
      { gb: 256, price: 549, original: 1099, wholesale: 500 },
      { gb: 512, price: 629, original: 1299, wholesale: 572 },
    ],
    grade: "excellent",
    batteryHealth: 89,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 74,
    stock: 52,
    features: ["Triple 12MP", "ProMotion 120Hz", "ProRAW", "LiDAR"],
    highlights: [
      "First Pro with 120Hz ProMotion",
      "Macro photography and ProRes video",
      "Telephoto with 3x optical zoom",
    ],
  },
  {
    id: "ip13pm",
    slug: "iphone-13-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 Pro Max",
    line: "iPhone 13",
    releaseYear: 2021,
    modelNumbers: "A2484",
    chip: "A15 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Sierra Blue", hex: "#a7c5e3", accent: "#7fa3c4", family: "Blue" },
      { name: "Alpine Green", hex: "#535f4f", accent: "#3e4a3b", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 559, original: 1099, wholesale: 509 },
      { gb: 256, price: 629, original: 1199, wholesale: 572 },
      { gb: 512, price: 729, original: 1399, wholesale: 663 },
      { gb: 1024, price: 829, original: 1599, wholesale: 754 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 103,
    stock: 44,
    popular: true,
    badge: "Best seller",
    features: ["Triple 12MP", "ProMotion 120Hz", '6.7" OLED', "ProRes"],
    highlights: [
      "Best-in-class battery endurance",
      "120Hz ProMotion on a huge canvas",
      "Pro camera system with 3x zoom",
    ],
  },
  {
    id: "ip14",
    slug: "iphone-14",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14",
    line: "iPhone 14",
    releaseYear: 2022,
    modelNumbers: "A2649",
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#a4c2dd", accent: "#7c9cb8", family: "Blue" },
      { name: "Purple", hex: "#d8d2e8", accent: "#b6afcc", family: "Purple" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
      { name: "Yellow", hex: "#f4dd86", accent: "#dcc25a", family: "Yellow" },
    ],
    storage: [
      { gb: 128, price: 499, original: 799, wholesale: 454 },
      { gb: 256, price: 569, original: 899, wholesale: 518 },
      { gb: 512, price: 649, original: 1099, wholesale: 591 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 69,
    stock: 88,
    features: ["Dual 12MP", "Crash Detection", "Super Retina XDR", "5G"],
    highlights: [
      "Crash Detection and Emergency SOS",
      "Improved main camera and Photonic Engine",
      "All-day battery with A15 efficiency",
    ],
  },
  {
    id: "ip14plus",
    slug: "iphone-14-plus",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Plus",
    line: "iPhone 14",
    releaseYear: 2022,
    modelNumbers: "A2632",
    chip: "A15 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#a4c2dd", accent: "#7c9cb8", family: "Blue" },
      { name: "Purple", hex: "#d8d2e8", accent: "#b6afcc", family: "Purple" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
      { name: "Yellow", hex: "#f4dd86", accent: "#dcc25a", family: "Yellow" },
    ],
    storage: [
      { gb: 128, price: 549, original: 899, wholesale: 500 },
      { gb: 256, price: 619, original: 999, wholesale: 563 },
      { gb: 512, price: 699, original: 1199, wholesale: 636 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 38,
    stock: 47,
    features: ["Dual 12MP", '6.7" OLED', "Crash Detection", "Best battery"],
    highlights: [
      "Biggest battery in a non-Pro iPhone",
      "Large 6.7-inch Super Retina XDR",
      "Lighter than a Pro Max",
    ],
  },
  {
    id: "ip14pro",
    slug: "iphone-14-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Pro",
    line: "iPhone 14",
    releaseYear: 2022,
    modelNumbers: "A2650",
    chip: "A16 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Space Black", hex: "#2b2c2e", accent: "#444548", family: "Black" },
      { name: "Silver", hex: "#e8e9e5", accent: "#c6c7c3", family: "Silver" },
      { name: "Gold", hex: "#f3e2c2", accent: "#d9c293", family: "Gold" },
      { name: "Deep Purple", hex: "#574f5e", accent: "#423b48", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 649, original: 999, wholesale: 591 },
      { gb: 256, price: 719, original: 1099, wholesale: 654 },
      { gb: 512, price: 819, original: 1299, wholesale: 745 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 85,
    stock: 54,
    features: ["48MP main", "Dynamic Island", "Always-On display", "ProMotion"],
    highlights: [
      "First 48MP Pro camera sensor",
      "Dynamic Island redefines the notch",
      "Always-On display with ProMotion",
    ],
  },
  {
    id: "ip14pm",
    slug: "iphone-14-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Pro Max",
    line: "iPhone 14",
    releaseYear: 2022,
    modelNumbers: "A2651",
    chip: "A16 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Space Black", hex: "#2b2c2e", accent: "#444548", family: "Black" },
      { name: "Silver", hex: "#e8e9e5", accent: "#c6c7c3", family: "Silver" },
      { name: "Gold", hex: "#f3e2c2", accent: "#d9c293", family: "Gold" },
      { name: "Deep Purple", hex: "#574f5e", accent: "#423b48", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 729, original: 1099, wholesale: 663 },
      { gb: 256, price: 799, original: 1199, wholesale: 727 },
      { gb: 512, price: 899, original: 1399, wholesale: 818 },
    ],
    grade: "pristine",
    batteryHealth: 92,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 117,
    stock: 38,
    popular: true,
    badge: "Best seller",
    features: ["48MP main", "Dynamic Island", '6.7" ProMotion', "Always-On"],
    highlights: [
      "Flagship 48MP camera with 2x crop zoom",
      "Brightest, biggest Always-On display",
      "Class-leading battery life",
    ],
  },
  {
    id: "ip15",
    slug: "iphone-15",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15",
    line: "iPhone 15",
    releaseYear: 2023,
    modelNumbers: "A2846",
    chip: "A16 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Black", hex: "#3a3d40", accent: "#54575b", family: "Black" },
      { name: "Blue", hex: "#cdd9d8", accent: "#a6b4b3", family: "Blue" },
      { name: "Green", hex: "#cfd9cd", accent: "#a8b4a6", family: "Green" },
      { name: "Yellow", hex: "#f4ead0", accent: "#dccfa8", family: "Yellow" },
      { name: "Pink", hex: "#f3dde0", accent: "#dbb9bf", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 629, original: 799, wholesale: 572 },
      { gb: 256, price: 699, original: 899, wholesale: 636 },
      { gb: 512, price: 799, original: 1099, wholesale: 727 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 78,
    stock: 92,
    popular: true,
    features: ["48MP main", "Dynamic Island", "USB-C", "5G"],
    highlights: [
      "48MP camera with 2x telephoto crop",
      "USB-C and Dynamic Island arrive",
      "Color-infused back glass",
    ],
  },
  {
    id: "ip15plus",
    slug: "iphone-15-plus",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Plus",
    line: "iPhone 15",
    releaseYear: 2023,
    modelNumbers: "A2847",
    chip: "A16 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Black", hex: "#3a3d40", accent: "#54575b", family: "Black" },
      { name: "Blue", hex: "#cdd9d8", accent: "#a6b4b3", family: "Blue" },
      { name: "Green", hex: "#cfd9cd", accent: "#a8b4a6", family: "Green" },
      { name: "Yellow", hex: "#f4ead0", accent: "#dccfa8", family: "Yellow" },
      { name: "Pink", hex: "#f3dde0", accent: "#dbb9bf", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 689, original: 899, wholesale: 627 },
      { gb: 256, price: 759, original: 999, wholesale: 691 },
      { gb: 512, price: 859, original: 1199, wholesale: 782 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 37,
    stock: 51,
    features: ["48MP main", '6.7" OLED', "USB-C", "Best battery"],
    highlights: [
      "Massive battery for two-day use",
      "Large 6.7-inch Super Retina XDR",
      "USB-C convenience at last",
    ],
  },
  {
    id: "ip15pro",
    slug: "iphone-15-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Pro",
    line: "iPhone 15",
    releaseYear: 2023,
    modelNumbers: "A2848",
    chip: "A17 Pro",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Natural Titanium", hex: "#b3ac9f", accent: "#928c80", family: "Titanium" },
      { name: "Blue Titanium", hex: "#56607a", accent: "#404960", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Black Titanium", hex: "#3d3d40", accent: "#56565a", family: "Titanium" },
    ],
    storage: [
      { gb: 128, price: 879, original: 999, wholesale: 800 },
      { gb: 256, price: 949, original: 1099, wholesale: 864 },
      { gb: 512, price: 1059, original: 1299, wholesale: 964 },
      { gb: 1024, price: 1169, original: 1499, wholesale: 1064 },
    ],
    grade: "pristine",
    batteryHealth: 94,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 89,
    stock: 46,
    features: ["48MP main", "A17 Pro", "Titanium", "Action button"],
    highlights: [
      "Lightweight aerospace-grade titanium",
      "A17 Pro enables console-class gaming",
      "Customizable Action button",
    ],
  },
  {
    id: "ip15pm",
    slug: "iphone-15-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Pro Max",
    line: "iPhone 15",
    releaseYear: 2023,
    modelNumbers: "A2849",
    chip: "A17 Pro",
    screen: 6.7,
    ram: 8,
    colors: [
      { name: "Natural Titanium", hex: "#b3ac9f", accent: "#928c80", family: "Titanium" },
      { name: "Blue Titanium", hex: "#56607a", accent: "#404960", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Black Titanium", hex: "#3d3d40", accent: "#56565a", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1019, original: 1199, wholesale: 927 },
      { gb: 512, price: 1149, original: 1399, wholesale: 1046 },
      { gb: 1024, price: 1329, original: 1599, wholesale: 1209 },
    ],
    grade: "pristine",
    batteryHealth: 95,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 121,
    stock: 31,
    popular: true,
    badge: "Best seller",
    features: ["5x Tetraprism", "A17 Pro", "Titanium", "Action button"],
    highlights: [
      "Exclusive 5x optical telephoto zoom",
      "Titanium build with the biggest battery",
      "A17 Pro for desktop-class performance",
    ],
  },
  {
    id: "ip16",
    slug: "iphone-16",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16",
    line: "iPhone 16",
    releaseYear: 2024,
    modelNumbers: "A3081",
    chip: "A18",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Black", hex: "#33363b", accent: "#4d5056", family: "Black" },
      { name: "White", hex: "#f1f1ec", accent: "#d2d2cd", family: "White" },
      { name: "Pink", hex: "#f4dde3", accent: "#dcb9c3", family: "Pink" },
      { name: "Teal", hex: "#a9c4c2", accent: "#82a09e", family: "Green" },
      { name: "Ultramarine", hex: "#8d9bd6", accent: "#6975b8", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 679, original: 799, wholesale: 618 },
      { gb: 256, price: 749, original: 899, wholesale: 682 },
      { gb: 512, price: 869, original: 1099, wholesale: 791 },
    ],
    grade: "pristine",
    batteryHealth: 96,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 53,
    stock: 104,
    popular: true,
    features: ["48MP Fusion", "A18", "Camera Control", "Action button"],
    highlights: [
      "New Camera Control button for quick capture",
      "A18 chip ready for Apple Intelligence",
      "Vivid color options and durable design",
    ],
  },
  {
    id: "ip16plus",
    slug: "iphone-16-plus",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16 Plus",
    line: "iPhone 16",
    releaseYear: 2024,
    modelNumbers: "A3082",
    chip: "A18",
    screen: 6.7,
    ram: 8,
    colors: [
      { name: "Black", hex: "#33363b", accent: "#4d5056", family: "Black" },
      { name: "White", hex: "#f1f1ec", accent: "#d2d2cd", family: "White" },
      { name: "Pink", hex: "#f4dde3", accent: "#dcb9c3", family: "Pink" },
      { name: "Teal", hex: "#a9c4c2", accent: "#82a09e", family: "Green" },
      { name: "Ultramarine", hex: "#8d9bd6", accent: "#6975b8", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 729, original: 899, wholesale: 663 },
      { gb: 256, price: 799, original: 999, wholesale: 727 },
      { gb: 512, price: 919, original: 1199, wholesale: 836 },
    ],
    grade: "pristine",
    batteryHealth: 96,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 26,
    stock: 61,
    features: ["48MP Fusion", "A18", "Camera Control", '6.7" OLED'],
    highlights: [
      "Bigger 6.7-inch display and longer battery",
      "A18 chip ready for Apple Intelligence",
      "New Camera Control button for quick capture",
    ],
  },
  {
    id: "ip16pro",
    slug: "iphone-16-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16 Pro",
    line: "iPhone 16",
    releaseYear: 2024,
    modelNumbers: "A3083",
    chip: "A18 Pro",
    screen: 6.3,
    ram: 8,
    colors: [
      { name: "Black Titanium", hex: "#3a3a3d", accent: "#535357", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Natural Titanium", hex: "#b6afa2", accent: "#948e82", family: "Titanium" },
      { name: "Desert Titanium", hex: "#bda47f", accent: "#9c8463", family: "Titanium" },
    ],
    storage: [
      { gb: 128, price: 899, original: 999, wholesale: 818 },
      { gb: 256, price: 969, original: 1099, wholesale: 882 },
      { gb: 512, price: 1089, original: 1299, wholesale: 991 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 67,
    stock: 42,
    features: ["48MP Fusion", "A18 Pro", "Camera Control", "5x zoom"],
    highlights: [
      "Larger 6.3-inch ProMotion display",
      "Pro camera with 5x telephoto and 4K120",
      "A18 Pro for advanced on-device AI",
    ],
  },
  {
    id: "ip16pm",
    slug: "iphone-16-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16 Pro Max",
    line: "iPhone 16",
    releaseYear: 2024,
    modelNumbers: "A3084",
    chip: "A18 Pro",
    screen: 6.9,
    ram: 8,
    colors: [
      { name: "Black Titanium", hex: "#3a3a3d", accent: "#535357", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Natural Titanium", hex: "#b6afa2", accent: "#948e82", family: "Titanium" },
      { name: "Desert Titanium", hex: "#bda47f", accent: "#9c8463", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1059, original: 1199, wholesale: 964 },
      { gb: 512, price: 1189, original: 1399, wholesale: 1082 },
      { gb: 1024, price: 1369, original: 1599, wholesale: 1246 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 93,
    stock: 28,
    popular: true,
    badge: "Best seller",
    features: ["48MP Fusion", "A18 Pro", '6.9" ProMotion', "5x zoom"],
    highlights: [
      "Largest iPhone display ever at 6.9 inches",
      "Pro camera system with 4K120 ProRes",
      "Best-in-class battery and performance",
    ],
  },
  {
    id: "ip16e",
    slug: "iphone-16e",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16e",
    line: "iPhone 16",
    releaseYear: 2025,
    modelNumbers: "A3212",
    chip: "A18",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Black", hex: "#2a2c30", accent: "#43464b", family: "Black" },
      { name: "White", hex: "#f3f3ee", accent: "#d4d4cf", family: "White" },
    ],
    storage: [
      { gb: 128, price: 549, original: 599, wholesale: 499 },
      { gb: 256, price: 619, original: 699, wholesale: 563 },
      { gb: 512, price: 739, original: 899, wholesale: 672 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "single",
    fiveG: true,
    rating: 4.6,
    reviews: 12,
    stock: 73,
    features: ["48MP Fusion", "A18", "Action button", "USB-C"],
    highlights: [
      "Essential iPhone with the A18 chip",
      "Apple Intelligence ready out of the box",
      "Long battery life and USB-C charging",
    ],
  },
  {
    id: "ip17",
    slug: "iphone-17",
    brand: "Apple",
    type: "phone",
    name: "iPhone 17",
    line: "iPhone 17",
    releaseYear: 2025,
    modelNumbers: "A3258",
    chip: "A19",
    screen: 6.3,
    ram: 8,
    colors: [
      { name: "Black", hex: "#2b2d31", accent: "#45484d", family: "Black" },
      { name: "White", hex: "#f4f4ef", accent: "#d5d5d0", family: "White" },
      { name: "Mist Blue", hex: "#bcd0e0", accent: "#92acc0", family: "Blue" },
      { name: "Sage", hex: "#b8c4a8", accent: "#94a382", family: "Green" },
      { name: "Lavender", hex: "#cfc6e6", accent: "#aa9fcc", family: "Purple" },
    ],
    storage: [
      { gb: 256, price: 779, original: 899, wholesale: 709 },
      { gb: 512, price: 899, original: 1099, wholesale: 818 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.8,
    reviews: 7,
    stock: 80,
    popular: true,
    features: ["48MP dual", "A19", '6.3" ProMotion', "120Hz"],
    highlights: [
      "120Hz ProMotion now on the base iPhone",
      "A19 chip with Apple Intelligence",
      "Brighter, bigger 6.3-inch display",
    ],
  },
  {
    id: "ipair",
    slug: "iphone-air",
    brand: "Apple",
    type: "phone",
    name: "iPhone Air",
    line: "iPhone Air",
    releaseYear: 2025,
    modelNumbers: "A3260",
    chip: "A19 Pro",
    screen: 6.5,
    ram: 12,
    colors: [
      { name: "Space Black", hex: "#2a2b2e", accent: "#434548", family: "Black" },
      { name: "Cloud White", hex: "#f3f2ed", accent: "#d4d3ce", family: "White" },
      { name: "Light Gold", hex: "#e8dcc4", accent: "#ccbf9f", family: "Gold" },
      { name: "Sky Blue", hex: "#bcd2e2", accent: "#92acc2", family: "Blue" },
    ],
    storage: [
      { gb: 256, price: 899, original: 999, wholesale: 818 },
      { gb: 512, price: 1019, original: 1199, wholesale: 927 },
      { gb: 1024, price: 1199, original: 1399, wholesale: 1091 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "single",
    fiveG: true,
    rating: 4.7,
    reviews: 7,
    stock: 38,
    badge: "Thinnest ever",
    features: ["48MP Fusion", "A19 Pro", "Titanium", "5.6mm thin"],
    highlights: [
      "The thinnest iPhone ever made at 5.6mm",
      "Titanium frame, feather-light in hand",
      "A19 Pro performance and efficiency",
    ],
  },
  {
    id: "ip17pro",
    slug: "iphone-17-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 17 Pro",
    line: "iPhone 17 Pro",
    releaseYear: 2025,
    modelNumbers: "A3256",
    chip: "A19 Pro",
    screen: 6.3,
    ram: 12,
    colors: [
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc0", family: "Silver" },
      { name: "Deep Blue", hex: "#2e4a6b", accent: "#456a93", family: "Blue" },
      { name: "Cosmic Orange", hex: "#e8703a", accent: "#c4592a", family: "Orange" },
    ],
    storage: [
      { gb: 256, price: 999, original: 1099, wholesale: 909 },
      { gb: 512, price: 1119, original: 1299, wholesale: 1018 },
      { gb: 1024, price: 1299, original: 1499, wholesale: 1182 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 8,
    stock: 30,
    popular: true,
    features: ["48MP triple", "A19 Pro", "8x zoom", "ProMotion"],
    highlights: [
      "Pro camera with longer optical zoom",
      "A19 Pro with vapor-chamber cooling",
      "Aluminum unibody and bigger battery",
    ],
  },
  {
    id: "ip17pm",
    slug: "iphone-17-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 17 Pro Max",
    line: "iPhone 17 Pro",
    releaseYear: 2025,
    modelNumbers: "A3257",
    chip: "A19 Pro",
    screen: 6.9,
    ram: 12,
    colors: [
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc0", family: "Silver" },
      { name: "Deep Blue", hex: "#2e4a6b", accent: "#456a93", family: "Blue" },
      { name: "Cosmic Orange", hex: "#e8703a", accent: "#c4592a", family: "Orange" },
    ],
    storage: [
      { gb: 256, price: 1199, original: 1299, wholesale: 1091 },
      { gb: 512, price: 1319, original: 1499, wholesale: 1200 },
      { gb: 1024, price: 1499, original: 1699, wholesale: 1364 },
      { gb: 2048, price: 1799, original: 1999, wholesale: 1637 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 10,
    stock: 22,
    popular: true,
    badge: "Best seller",
    features: ["48MP triple", "A19 Pro", '6.9" ProMotion', "8x zoom"],
    highlights: [
      "The largest, longest-lasting iPhone",
      "Pro camera system with 8x telephoto",
      "Up to 2TB of storage",
    ],
  },
  {
    id: "ipse2020",
    slug: "iphone-se-2020",
    brand: "Apple",
    type: "phone",
    name: "iPhone SE (2020)",
    line: "iPhone SE",
    releaseYear: 2020,
    modelNumbers: "A2275",
    chip: "A13 Bionic",
    screen: 4.7,
    ram: 3,
    colors: [
      { name: "Black", hex: "#1d1d1f", accent: "#3a3a3c", family: "Black" },
      { name: "White", hex: "#faf9f5", accent: "#dad9d3", family: "White" },
      { name: "Red", hex: "#ba0c2e", accent: "#8c0922", family: "Red" },
    ],
    storage: [
      { gb: 64, price: 129, original: 399, wholesale: 118 },
      { gb: 128, price: 159, original: 449, wholesale: 145 },
      { gb: 256, price: 199, original: 549, wholesale: 181 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "single",
    fiveG: false,
    rating: 4.3,
    reviews: 55,
    stock: 6,
    features: ["12MP single", "Touch ID", "A13 Bionic", '4.7" Retina'],
    highlights: [
      "Pocket-sized with classic Touch ID",
      "Flagship A13 chip at a budget price",
      "Familiar home-button design",
    ],
  },
  {
    id: "ipse2022",
    slug: "iphone-se-2022",
    brand: "Apple",
    type: "phone",
    name: "iPhone SE (2022)",
    line: "iPhone SE",
    releaseYear: 2022,
    modelNumbers: "A2595",
    chip: "A15 Bionic",
    screen: 4.7,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 64, price: 159, original: 429, wholesale: 145 },
      { gb: 128, price: 199, original: 479, wholesale: 181 },
      { gb: 256, price: 239, original: 579, wholesale: 218 },
    ],
    grade: "good",
    batteryHealth: 88,
    cameraLayout: "single",
    fiveG: true,
    rating: 4.4,
    reviews: 46,
    stock: 67,
    badge: "Budget pick",
    features: ["12MP single", "Touch ID", "A15 Bionic", "5G"],
    highlights: [
      "Flagship A15 chip at an entry price",
      "Classic Touch ID home button",
      "Compact and pocket-friendly",
    ],
  },
  {
    id: "s21",
    slug: "galaxy-s21",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S21",
    line: "Galaxy S21",
    releaseYear: 2021,
    modelNumbers: "SM-G991U",
    chip: "Snapdragon 888",
    screen: 6.2,
    ram: 8,
    colors: [
      { name: "Phantom Gray", hex: "#4f4f53", accent: "#3a3a3d", family: "Gray" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Phantom Violet", hex: "#c9bfd6", accent: "#a79cb8", family: "Purple" },
      { name: "Phantom Pink", hex: "#f0d8d3", accent: "#d8b4ac", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 259, original: 799, wholesale: 236 },
      { gb: 256, price: 309, original: 849, wholesale: 281 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 70,
    stock: 73,
    features: ["Triple camera", "120Hz AMOLED", "Snapdragon 888", "5G"],
    highlights: [
      "Smooth 120Hz Dynamic AMOLED",
      "Versatile triple-camera setup",
      "Compact flagship feel",
    ],
  },
  {
    id: "s21u",
    slug: "galaxy-s21-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S21 Ultra",
    line: "Galaxy S21",
    releaseYear: 2021,
    modelNumbers: "SM-G998U",
    chip: "Snapdragon 888",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom Silver", hex: "#d9dadc", accent: "#b7b8ba", family: "Silver" },
      { name: "Phantom Titanium", hex: "#6b6c70", accent: "#525357", family: "Gray" },
      { name: "Phantom Navy", hex: "#2f3a4d", accent: "#465570", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 379, original: 1199, wholesale: 345 },
      { gb: 256, price: 439, original: 1249, wholesale: 400 },
      { gb: 512, price: 509, original: 1379, wholesale: 463 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.6,
    reviews: 87,
    stock: 49,
    features: ["108MP quad", "100x Space Zoom", "120Hz QHD+", "S Pen support"],
    highlights: [
      "108MP sensor with 100x Space Zoom",
      "Dual telephoto for flexible reach",
      "First S Ultra with S Pen support",
    ],
  },
  {
    id: "s22",
    slug: "galaxy-s22",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S22",
    line: "Galaxy S22",
    releaseYear: 2022,
    modelNumbers: "SM-S901U",
    chip: "Snapdragon 8 Gen 1",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Pink Gold", hex: "#f1ddd0", accent: "#d9bda9", family: "Pink" },
      { name: "Green", hex: "#bcc6b3", accent: "#98a48d", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 329, original: 799, wholesale: 299 },
      { gb: 256, price: 389, original: 849, wholesale: 354 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 66,
    stock: 71,
    features: ["50MP triple", "120Hz AMOLED", "Snapdragon 8 Gen 1", "5G"],
    highlights: [
      "Upgraded 50MP main sensor",
      "Compact body with premium glass",
      "Bright 120Hz adaptive display",
    ],
  },
  {
    id: "s22u",
    slug: "galaxy-s22-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S22 Ultra",
    line: "Galaxy S22",
    releaseYear: 2022,
    modelNumbers: "SM-S908U",
    chip: "Snapdragon 8 Gen 1",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Green", hex: "#3f4a3c", accent: "#5d6b58", family: "Green" },
      { name: "Burgundy", hex: "#5c2a33", accent: "#7d3a45", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 469, original: 1199, wholesale: 427 },
      { gb: 256, price: 529, original: 1299, wholesale: 481 },
      { gb: 512, price: 609, original: 1399, wholesale: 554 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.7,
    reviews: 95,
    stock: 45,
    popular: true,
    badge: "S Pen",
    features: ["108MP quad", "Built-in S Pen", "100x Space Zoom", "120Hz QHD+"],
    highlights: [
      "Built-in S Pen returns in Ultra",
      "108MP camera with 100x Space Zoom",
      "Note-style productivity powerhouse",
    ],
  },
  {
    id: "s23",
    slug: "galaxy-s23",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23",
    line: "Galaxy S23",
    releaseYear: 2023,
    modelNumbers: "SM-S911U",
    chip: "Snapdragon 8 Gen 2",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Green", hex: "#a7b4a0", accent: "#82917a", family: "Green" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
      { name: "Graphite", hex: "#54565a", accent: "#3e4044", family: "Gray" },
    ],
    storage: [
      { gb: 128, price: 449, original: 799, wholesale: 409 },
      { gb: 256, price: 509, original: 859, wholesale: 463 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.6,
    reviews: 61,
    stock: 64,
    features: ["50MP triple", "Snapdragon 8 Gen 2", "120Hz AMOLED", "5G"],
    highlights: [
      "Efficient Snapdragon 8 Gen 2 for Galaxy",
      "Excellent battery in a compact frame",
      "Refined contour-cut camera design",
    ],
  },
  {
    id: "s23u",
    slug: "galaxy-s23-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23 Ultra",
    line: "Galaxy S23",
    releaseYear: 2023,
    modelNumbers: "SM-S918U",
    chip: "Snapdragon 8 Gen 2",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Green", hex: "#3f4a3c", accent: "#5d6b58", family: "Green" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
      { name: "Sky Blue", hex: "#a9c6e0", accent: "#7fa3c4", family: "Blue" },
    ],
    storage: [
      { gb: 256, price: 619, original: 1199, wholesale: 563 },
      { gb: 512, price: 699, original: 1379, wholesale: 636 },
      { gb: 1024, price: 819, original: 1619, wholesale: 745 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.8,
    reviews: 101,
    stock: 39,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Built-in S Pen", "100x Space Zoom", "120Hz QHD+"],
    highlights: [
      "Massive 200MP main camera sensor",
      "Integrated S Pen for notes and art",
      "Snapdragon 8 Gen 2 with vapor cooling",
    ],
  },
  {
    id: "s24",
    slug: "galaxy-s24",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S24",
    line: "Galaxy S24",
    releaseYear: 2024,
    modelNumbers: "SM-S921U",
    chip: "Snapdragon 8 Gen 3",
    screen: 6.2,
    ram: 8,
    colors: [
      { name: "Onyx Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Marble Gray", hex: "#9a9b9d", accent: "#7a7b7d", family: "Gray" },
      { name: "Cobalt Violet", hex: "#9a93c7", accent: "#7670a8", family: "Purple" },
      { name: "Amber Yellow", hex: "#e8d39a", accent: "#cdb877", family: "Yellow" },
    ],
    storage: [
      { gb: 128, price: 599, original: 799, wholesale: 545 },
      { gb: 256, price: 659, original: 859, wholesale: 600 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 45,
    stock: 81,
    features: ["50MP triple", "Galaxy AI", "120Hz AMOLED", "Snapdragon 8 Gen 3"],
    highlights: [
      "Galaxy AI features built in",
      "Brighter, flatter 120Hz display",
      "Seven years of OS updates",
    ],
  },
  {
    id: "s24u",
    slug: "galaxy-s24-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S24 Ultra",
    line: "Galaxy S24",
    releaseYear: 2024,
    modelNumbers: "SM-S928U",
    chip: "Snapdragon 8 Gen 3",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Titanium Black", hex: "#3a3a3c", accent: "#535355", family: "Titanium" },
      { name: "Titanium Gray", hex: "#9c9c9e", accent: "#7c7c7e", family: "Titanium" },
      { name: "Titanium Violet", hex: "#b6aec4", accent: "#938aa6", family: "Titanium" },
      { name: "Titanium Yellow", hex: "#e6d8a8", accent: "#cabd86", family: "Titanium" },
      { name: "Titanium Blue", hex: "#aebccb", accent: "#8b9aac", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 939, original: 1299, wholesale: 854 },
      { gb: 512, price: 1029, original: 1419, wholesale: 936 },
      { gb: 1024, price: 1169, original: 1659, wholesale: 1064 },
    ],
    grade: "pristine",
    batteryHealth: 95,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.8,
    reviews: 84,
    stock: 36,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Titanium frame", "Built-in S Pen", "Galaxy AI"],
    highlights: [
      "Durable titanium build with flat display",
      "200MP camera and improved zoom AI",
      "Galaxy AI and integrated S Pen",
    ],
  },
  {
    id: "s25u",
    slug: "galaxy-s25-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S25 Ultra",
    line: "Galaxy S25",
    releaseYear: 2025,
    modelNumbers: "SM-S938U",
    chip: "Snapdragon 8 Elite",
    screen: 6.9,
    ram: 12,
    colors: [
      { name: "Titanium Black", hex: "#3a3a3c", accent: "#535355", family: "Titanium" },
      { name: "Titanium Silverblue", hex: "#c4ccd4", accent: "#a0a8b0", family: "Titanium" },
      { name: "Titanium Whitesilver", hex: "#e7e7e4", accent: "#c5c5c2", family: "Titanium" },
      { name: "Titanium Gray", hex: "#8f9092", accent: "#707173", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1049, original: 1299, wholesale: 954 },
      { gb: 512, price: 1149, original: 1419, wholesale: 1046 },
      { gb: 1024, price: 1289, original: 1659, wholesale: 1173 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.9,
    reviews: 26,
    stock: 27,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Snapdragon 8 Elite", "Built-in S Pen", "Galaxy AI"],
    highlights: [
      "Snapdragon 8 Elite for Galaxy power",
      "Larger 6.9-inch display, slimmer bezels",
      "Advanced Galaxy AI with built-in S Pen",
    ],
  },
  {
    id: "s20fe",
    slug: "galaxy-s20-fe-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S20 FE 5G",
    line: "Galaxy S20",
    releaseYear: 2020,
    modelNumbers: "SM-G781U",
    chip: "Snapdragon 865",
    screen: 6.5,
    ram: 6,
    colors: [
      { name: "Cloud Navy", hex: "#34415e", accent: "#4a5b80", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 199, original: 699, wholesale: 181 },
      { gb: 256, price: 239, original: 749, wholesale: 218 },
    ],
    grade: "good",
    batteryHealth: 84,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.4,
    reviews: 48,
    stock: 0,
    features: ["Triple camera", "120Hz AMOLED", "Snapdragon 865", "5G"],
    highlights: [
      "Flagship features at a fan-edition price",
      "Smooth 120Hz Super AMOLED display",
      "Versatile triple-camera system",
    ],
  },
  {
    id: "s21fe",
    slug: "galaxy-s21-fe-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S21 FE 5G",
    line: "Galaxy S21",
    releaseYear: 2022,
    modelNumbers: "SM-G990U",
    chip: "Snapdragon 888",
    screen: 6.4,
    ram: 6,
    colors: [
      { name: "Graphite", hex: "#54565a", accent: "#3e4044", family: "Gray" },
      { name: "Lavender", hex: "#c9bede", accent: "#a698c2", family: "Purple" },
      { name: "White", hex: "#f0efeb", accent: "#d1d0cc", family: "White" },
    ],
    storage: [
      { gb: 128, price: 239, original: 699, wholesale: 218 },
      { gb: 256, price: 289, original: 769, wholesale: 263 },
    ],
    grade: "good",
    batteryHealth: 85,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.4,
    reviews: 38,
    stock: 4,
    features: ["Triple camera", "120Hz AMOLED", "Snapdragon 888", "5G"],
    highlights: [
      "Fan Edition flagship value",
      "120Hz display with slim bezels",
      "All-day 4500mAh battery",
    ],
  },
  {
    id: "s22plus",
    slug: "galaxy-s22-plus",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S22+",
    line: "Galaxy S22",
    releaseYear: 2022,
    modelNumbers: "SM-S906U",
    chip: "Snapdragon 8 Gen 1",
    screen: 6.6,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Green", hex: "#bcc6b3", accent: "#98a48d", family: "Green" },
      { name: "Pink Gold", hex: "#f1ddd0", accent: "#d9bda9", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 399, original: 999, wholesale: 363 },
      { gb: 256, price: 459, original: 1049, wholesale: 418 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 37,
    stock: 52,
    features: ["50MP triple", "120Hz AMOLED", '6.6" display', "5G"],
    highlights: [
      "Larger 6.6-inch display and battery",
      "50MP main camera with Nightography",
      "Bright adaptive 120Hz screen",
    ],
  },
  {
    id: "s23fe",
    slug: "galaxy-s23-fe",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23 FE",
    line: "Galaxy S23",
    releaseYear: 2023,
    modelNumbers: "SM-S711U",
    chip: "Snapdragon 8 Gen 1",
    screen: 6.4,
    ram: 8,
    colors: [
      { name: "Mint", hex: "#cfe6d6", accent: "#a8cdb8", family: "Green" },
      { name: "Graphite", hex: "#54565a", accent: "#3e4044", family: "Gray" },
    ],
    storage: [
      { gb: 128, price: 349, original: 599, wholesale: 318 },
      { gb: 256, price: 399, original: 659, wholesale: 363 },
    ],
    grade: "excellent",
    batteryHealth: 89,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 26,
    stock: 57,
    features: ["50MP triple", "120Hz AMOLED", "Exynos 2200", "5G"],
    highlights: [
      "Fan Edition with a 50MP main camera",
      "Large 4500mAh battery",
      "Smooth 120Hz Super AMOLED",
    ],
  },
  {
    id: "s23plus",
    slug: "galaxy-s23-plus",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23+",
    line: "Galaxy S23",
    releaseYear: 2023,
    modelNumbers: "SM-S916U",
    chip: "Snapdragon 8 Gen 2",
    screen: 6.6,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
    ],
    storage: [
      { gb: 256, price: 559, original: 999, wholesale: 508 },
      { gb: 512, price: 639, original: 1119, wholesale: 581 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.6,
    reviews: 31,
    stock: 44,
    features: ["50MP triple", "Snapdragon 8 Gen 2", '6.6" AMOLED', "5G"],
    highlights: [
      "Bigger battery and display than the S23",
      "Snapdragon 8 Gen 2 for Galaxy",
      "Refined contour-cut camera design",
    ],
  },
  {
    id: "s24plus",
    slug: "galaxy-s24-plus",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S24+",
    line: "Galaxy S24",
    releaseYear: 2024,
    modelNumbers: "SM-S926U",
    chip: "Snapdragon 8 Gen 3",
    screen: 6.7,
    ram: 12,
    colors: [
      { name: "Onyx Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
    ],
    storage: [
      { gb: 256, price: 699, original: 999, wholesale: 636 },
      { gb: 512, price: 789, original: 1119, wholesale: 718 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 29,
    stock: 49,
    features: ["50MP triple", "Galaxy AI", "120Hz QHD+", "Snapdragon 8 Gen 3"],
    highlights: [
      "Sharper QHD+ 120Hz display",
      "Galaxy AI features built in",
      "Bigger battery for all-day power",
    ],
  },
  {
    id: "s25",
    slug: "galaxy-s25",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S25",
    line: "Galaxy S25",
    releaseYear: 2025,
    modelNumbers: "SM-S931U",
    chip: "Snapdragon 8 Elite",
    screen: 6.2,
    ram: 12,
    colors: [
      { name: "Navy", hex: "#2f3a52", accent: "#46557a", family: "Blue" },
      { name: "Icy Blue", hex: "#bcd6e8", accent: "#93b3cc", family: "Blue" },
      { name: "Mint", hex: "#cfe6d6", accent: "#a8cdb8", family: "Green" },
      { name: "Silver Shadow", hex: "#c9cacc", accent: "#a6a7a9", family: "Silver" },
    ],
    storage: [
      { gb: 128, price: 699, original: 799, wholesale: 636 },
      { gb: 256, price: 759, original: 859, wholesale: 690 },
    ],
    grade: "pristine",
    batteryHealth: 96,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 20,
    stock: 62,
    features: ["50MP triple", "Snapdragon 8 Elite", "Galaxy AI", "120Hz AMOLED"],
    highlights: [
      "Snapdragon 8 Elite for Galaxy",
      "Upgraded Galaxy AI experiences",
      "Compact flagship with seven years of updates",
    ],
  },
  {
    id: "s25plus",
    slug: "galaxy-s25-plus",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S25+",
    line: "Galaxy S25",
    releaseYear: 2025,
    modelNumbers: "SM-S936U",
    chip: "Snapdragon 8 Elite",
    screen: 6.7,
    ram: 12,
    colors: [
      { name: "Navy", hex: "#2f3a52", accent: "#46557a", family: "Blue" },
    ],
    storage: [
      { gb: 256, price: 849, original: 999, wholesale: 772 },
      { gb: 512, price: 939, original: 1119, wholesale: 854 },
    ],
    grade: "pristine",
    batteryHealth: 96,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.8,
    reviews: 17,
    stock: 41,
    features: ["50MP triple", "Snapdragon 8 Elite", "120Hz QHD+", "Galaxy AI"],
    highlights: [
      "Larger QHD+ 120Hz display",
      "Snapdragon 8 Elite performance",
      "Galaxy AI with all-day battery",
    ],
  },
  {
    id: "s26",
    slug: "galaxy-s26",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S26",
    line: "Galaxy S26",
    releaseYear: 2026,
    modelNumbers: "SM-S942U",
    chip: "Snapdragon 8 Elite Gen 5",
    screen: 6.3,
    ram: 12,
    colors: [
      { name: "Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "White", hex: "#f0f0ec", accent: "#d0d0cc", family: "White" },
    ],
    storage: [
      { gb: 256, price: 799, original: 899, wholesale: 727 },
      { gb: 512, price: 899, original: 999, wholesale: 818 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.8,
    reviews: 7,
    stock: 70,
    features: ["50MP triple", "Snapdragon 8 Elite Gen 2", "Galaxy AI", "120Hz AMOLED"],
    highlights: [
      "Latest Snapdragon 8 Elite Gen 2 power",
      "Next-gen Galaxy AI built in",
      "Refined compact flagship design",
    ],
  },
  {
    id: "s26u",
    slug: "galaxy-s26-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S26 Ultra",
    line: "Galaxy S26",
    releaseYear: 2026,
    modelNumbers: "SM-S948U",
    chip: "Snapdragon 8 Elite Gen 5",
    screen: 6.9,
    ram: 16,
    colors: [
      { name: "Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "White", hex: "#f0f0ec", accent: "#d0d0cc", family: "White" },
      { name: "Violet", hex: "#6f5f96", accent: "#897ab0", family: "Purple" },
      { name: "Sky Blue", hex: "#bcd6e8", accent: "#93b3cc", family: "Blue" },
    ],
    storage: [
      { gb: 256, price: 1199, original: 1299, wholesale: 1091 },
      { gb: 512, price: 1319, original: 1499, wholesale: 1200 },
      { gb: 1024, price: 1499, original: 1699, wholesale: 1364 },
    ],
    grade: "pristine",
    batteryHealth: 99,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.9,
    reviews: 8,
    stock: 33,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Snapdragon 8 Elite Gen 2", "Built-in S Pen", "Galaxy AI"],
    highlights: [
      "Flagship 200MP camera system",
      "Next-gen Galaxy AI with built-in S Pen",
      "Largest 6.9-inch display and battery",
    ],
  },
  {
    id: "zflip5",
    slug: "galaxy-z-flip5",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy Z Flip5",
    line: "Galaxy Z Flip",
    releaseYear: 2023,
    modelNumbers: "SM-F731U",
    chip: "Snapdragon 8 Gen 2",
    screen: 6.7,
    ram: 8,
    colors: [
      { name: "Mint", hex: "#bcd6cb", accent: "#97b4a8", family: "Green" },
      { name: "Graphite", hex: "#3c3d40", accent: "#56575b", family: "Gray" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
    ],
    storage: [
      { gb: 256, price: 549, original: 999, wholesale: 500 },
      { gb: 512, price: 629, original: 1119, wholesale: 572 },
    ],
    grade: "excellent",
    batteryHealth: 89,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 52,
    stock: 43,
    badge: "Foldable",
    features: ["Flex Window", "Foldable AMOLED", "Snapdragon 8 Gen 2", "5G"],
    highlights: [
      "Large 3.4-inch Flex Window cover screen",
      "Folds to a truly pocketable square",
      "Flagship power in a flip design",
    ],
  },
  {
    id: "zfold5",
    slug: "galaxy-z-fold5",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy Z Fold5",
    line: "Galaxy Z Fold",
    releaseYear: 2023,
    modelNumbers: "SM-F946U",
    chip: "Snapdragon 8 Gen 2",
    screen: 7.6,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Icy Blue", hex: "#c2d2d6", accent: "#9eaeb2", family: "Blue" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
    ],
    storage: [
      { gb: 256, price: 899, original: 1799, wholesale: 818 },
      { gb: 512, price: 999, original: 1919, wholesale: 909 },
      { gb: 1024, price: 1149, original: 2159, wholesale: 1046 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 43,
    stock: 29,
    badge: "Foldable",
    features: ['7.6" main display', "S Pen support", "Flex Hinge", "Snapdragon 8 Gen 2"],
    highlights: [
      "Tablet-sized 7.6-inch folding display",
      "Multitasking with Flex Mode and S Pen",
      "Slimmer hinge and lighter body",
    ],
  },
  {
    id: "a54",
    slug: "galaxy-a54-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A54 5G",
    line: "Galaxy A54",
    releaseYear: 2023,
    modelNumbers: "SM-A546U",
    chip: "Exynos 1380",
    screen: 6.4,
    ram: 6,
    colors: [
      { name: "Awesome Graphite", hex: "#3a3b3e", accent: "#535458", family: "Gray" },
      { name: "Awesome White", hex: "#edece7", accent: "#cbcac5", family: "White" },
      { name: "Awesome Violet", hex: "#b6aec9", accent: "#928aa6", family: "Purple" },
      { name: "Awesome Lime", hex: "#c3cf9f", accent: "#9faa7c", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 269, original: 449, wholesale: 245 },
    ],
    grade: "good",
    batteryHealth: 90,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.5,
    reviews: 57,
    stock: 88,
    badge: "Budget pick",
    features: ["50MP triple", "120Hz Super AMOLED", "Exynos 1380", "5G"],
    highlights: [
      "Premium features at a mid-range price",
      "Smooth 120Hz Super AMOLED screen",
      "Large battery for all-day use",
    ],
  },
  {
    id: "a14",
    slug: "galaxy-a14-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A14 5G",
    line: "Galaxy A14",
    releaseYear: 2023,
    modelNumbers: "SM-A146U",
    chip: "Dimensity 700",
    screen: 6.6,
    ram: 4,
    colors: [
      { name: "Black", hex: "#2b2c2e", accent: "#444547", family: "Black" },
    ],
    storage: [
      { gb: 64, price: 119, original: 249, wholesale: 108 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.3,
    reviews: 53,
    stock: 96,
    badge: "Budget pick",
    features: ["50MP triple", '6.6" display', "5000mAh battery", "5G"],
    highlights: [
      "Affordable 5G with a big battery",
      "Large 6.6-inch display",
      "Everyday triple-camera setup",
    ],
  },
  {
    id: "a16",
    slug: "galaxy-a16",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A16",
    line: "Galaxy A16",
    releaseYear: 2024,
    modelNumbers: "SM-A166U",
    chip: "Exynos 1330",
    screen: 6.7,
    ram: 4,
    colors: [
      { name: "Light Gray", hex: "#cfd0d2", accent: "#adaeb0", family: "Silver" },
      { name: "Blue Black", hex: "#2b3038", accent: "#444b56", family: "Black" },
      { name: "Light Green", hex: "#c4dcc0", accent: "#9fbe9a", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 149, original: 199, wholesale: 136 },
    ],
    grade: "good",
    batteryHealth: 90,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.3,
    reviews: 33,
    stock: 104,
    badge: "Budget pick",
    features: ["50MP triple", "90Hz AMOLED", "5000mAh battery", "5G"],
    highlights: [
      "Big 6.7-inch Super AMOLED display",
      "Six years of OS and security updates",
      "All-day 5000mAh battery",
    ],
  },
  {
    id: "a17",
    slug: "galaxy-a17-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A17 5G",
    line: "Galaxy A17",
    releaseYear: 2025,
    modelNumbers: "SM-A176U",
    chip: "Exynos 1330",
    screen: 6.7,
    ram: 4,
    colors: [
      { name: "Gray", hex: "#8f9092", accent: "#707173", family: "Gray" },
      { name: "Blue", hex: "#3a4a6b", accent: "#51648f", family: "Blue" },
      { name: "Black", hex: "#2b2c2e", accent: "#444547", family: "Black" },
    ],
    storage: [
      { gb: 128, price: 179, original: 249, wholesale: 163 },
    ],
    grade: "good",
    batteryHealth: 92,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.4,
    reviews: 18,
    stock: 88,
    badge: "Budget pick",
    features: ["50MP triple", "90Hz AMOLED", "5000mAh battery", "5G"],
    highlights: [
      "Affordable 5G with a Super AMOLED screen",
      "Six years of OS updates",
      "Reliable all-day battery",
    ],
  },
  {
    id: "a37",
    slug: "galaxy-a37",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A37",
    line: "Galaxy A37",
    releaseYear: 2026,
    modelNumbers: "SM-A376U",
    chip: "Exynos 1480",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Awesome Charcoal", hex: "#2b2c2e", accent: "#444547", family: "Black" },
    ],
    storage: [
      { gb: 128, price: 199, original: 279, wholesale: 181 },
      { gb: 256, price: 229, original: 309, wholesale: 209 },
    ],
    grade: "good",
    batteryHealth: 93,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.4,
    reviews: 12,
    stock: 9,
    badge: "Budget pick",
    features: ["50MP triple", "120Hz AMOLED", "5000mAh battery", "5G"],
    highlights: [
      "Mid-range value with a 120Hz screen",
      "Durable design with Galaxy AI basics",
      "Big battery for all-day use",
    ],
  },
  {
    id: "ipad9",
    slug: "ipad-9th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (9th gen)",
    line: "iPad",
    releaseYear: 2021,
    modelNumbers: "A2602 / A2604",
    chip: "A13 Bionic",
    screen: 10.2,
    ram: 3,
    image: "/photos/ipad-9th-gen.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
    ],
    storage: [
      { gb: 64, price: 199, original: 329, wholesale: 181 },
      { gb: 256, price: 279, original: 479, wholesale: 254 },
    ],
    grade: "good",
    batteryHealth: 93,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 99,
    stock: 124,
    badge: "Budget pick",
    features: ["A13 Bionic", '10.2" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "Most affordable way into iPadOS",
      "Reliable A13 for everyday tasks",
      "Works with Apple Pencil and keyboards",
    ],
  },
  {
    id: "ipad10",
    slug: "ipad-10th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (10th gen)",
    line: "iPad",
    releaseYear: 2022,
    modelNumbers: "A2696 / A2757",
    chip: "A14 Bionic",
    screen: 10.9,
    ram: 4,
    image: "/photos/ipad-10th-gen.jpg",
    colors: [
      { name: "Blue", hex: "#7da3b8", accent: "#5c8298", family: "Blue", image: "/photos/ipad-10th-gen-blue.jpg" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink", image: "/photos/ipad-10th-gen-pink.jpg" },
      { name: "Yellow", hex: "#ecd98c", accent: "#cfbb67", family: "Yellow", image: "/photos/ipad-10th-gen-yellow.jpg" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver", image: "/photos/ipad-10th-gen-silver.jpg" },
    ],
    storage: [
      { gb: 64, price: 269, original: 449, wholesale: 245 },
      { gb: 256, price: 349, original: 599, wholesale: 318 },
    ],
    grade: "excellent",
    batteryHealth: 94,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 64,
    stock: 97,
    features: ["A14 Bionic", '10.9" Liquid Retina', "USB-C", "Landscape camera"],
    highlights: [
      "All-screen design in fun colors",
      "Landscape front camera for video calls",
      "USB-C and Apple Pencil support",
    ],
  },
  {
    id: "ipadmini6",
    slug: "ipad-mini-6",
    brand: "Apple",
    type: "tablet",
    name: "iPad mini (6th gen)",
    line: "iPad mini",
    releaseYear: 2021,
    modelNumbers: "A2567 / A2568",
    chip: "A15 Bionic",
    screen: 8.3,
    ram: 4,
    image: "/photos/ipad-mini-6.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink" },
      { name: "Purple", hex: "#c3bcd2", accent: "#9f98b4", family: "Purple" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
    ],
    storage: [
      { gb: 64, price: 319, original: 499, wholesale: 290 },
      { gb: 256, price: 419, original: 649, wholesale: 381 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.7,
    reviews: 54,
    stock: 58,
    features: ["A15 Bionic", '8.3" Liquid Retina', "Touch ID", "Apple Pencil 2"],
    highlights: [
      "Ultra-portable full-power iPad",
      "Edge-to-edge 8.3-inch display",
      "Apple Pencil 2 support with USB-C",
    ],
  },
  {
    id: "ipadair5",
    slug: "ipad-air-5-m1",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air (5th gen, M1)",
    line: "iPad Air",
    releaseYear: 2022,
    modelNumbers: "A2588 / A2589",
    chip: "Apple M1",
    screen: 10.9,
    ram: 8,
    image: "/photos/ipad-air-5-m1.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#9fc0cf", accent: "#789fb0", family: "Blue" },
      { name: "Purple", hex: "#c8c2dc", accent: "#a39cbe", family: "Purple" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink" },
    ],
    storage: [
      { gb: 64, price: 399, original: 599, wholesale: 363 },
      { gb: 256, price: 499, original: 749, wholesale: 454 },
    ],
    grade: "excellent",
    batteryHealth: 95,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.8,
    reviews: 71,
    stock: 62,
    popular: true,
    badge: "Great value",
    features: ["Apple M1", '10.9" Liquid Retina', "USB-C", "Apple Pencil 2"],
    highlights: [
      "Desktop-class M1 chip in a thin Air",
      "Vivid 10.9-inch Liquid Retina display",
      "Center Stage front camera",
    ],
  },
  {
    id: "ipadair11m2",
    slug: "ipad-air-11-m2",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Air 11" (M2)',
    line: "iPad Air",
    releaseYear: 2024,
    modelNumbers: "A2902 / A2903",
    chip: "Apple M2",
    screen: 11,
    ram: 8,
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#aebfc9", accent: "#899ba6", family: "Blue" },
      { name: "Purple", hex: "#c4bdd0", accent: "#9f98b2", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 469, original: 599, wholesale: 427 },
      { gb: 256, price: 549, original: 699, wholesale: 500 },
      { gb: 512, price: 679, original: 899, wholesale: 618 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.8,
    reviews: 35,
    stock: 48,
    features: ["Apple M2", '11" Liquid Retina', "USB-C", "Apple Pencil Pro"],
    highlights: [
      "Powerful M2 chip for creative work",
      "Landscape Center Stage camera",
      "Apple Pencil Pro and Magic Keyboard ready",
    ],
  },
  {
    id: "ipadpro11m4",
    slug: "ipad-pro-11-m4",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 11" (M4)',
    line: "iPad Pro",
    releaseYear: 2024,
    modelNumbers: "A2836 / A2837",
    chip: "Apple M4",
    screen: 11,
    ram: 8,
    colors: [
      { name: "Space Black", hex: "#2a2b2e", accent: "#45464a", family: "Black" },
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc1", family: "Silver" },
    ],
    storage: [
      { gb: 256, price: 799, original: 999, wholesale: 727 },
      { gb: 512, price: 949, original: 1199, wholesale: 864 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.9,
    reviews: 20,
    stock: 26,
    badge: "Tandem OLED",
    features: ["M4 chip", "Ultra Retina XDR", "Tandem OLED", "Thinnest ever"],
    highlights: [
      "Stunning Tandem OLED Ultra Retina XDR display",
      "M4 chip outpaces most laptops",
      "Incredibly thin and light Pro design",
    ],
  },
  {
    id: "ipadpro13m4",
    slug: "ipad-pro-13-m4",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 13" (M4)',
    line: "iPad Pro",
    releaseYear: 2024,
    modelNumbers: "A2925 / A2926",
    chip: "Apple M4",
    screen: 13,
    ram: 8,
    colors: [
      { name: "Space Black", hex: "#2a2b2e", accent: "#45464a", family: "Black" },
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc1", family: "Silver" },
    ],
    storage: [
      { gb: 256, price: 949, original: 1299, wholesale: 879 },
      { gb: 512, price: 1099, original: 1499, wholesale: 1019 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.9,
    reviews: 13,
    stock: 22,
    badge: "Tandem OLED",
    features: ["M4 chip", "Ultra Retina XDR", "Tandem OLED", "Thinnest ever"],
    highlights: [
      "Stunning Tandem OLED Ultra Retina XDR display",
      "M4 chip outpaces most laptops",
      "Thinnest Apple product ever made",
    ],
  },

  // ---- Earlier iPads carried in live warehouse stock -----------------------
  // Classic home-button models reuse the iPad (9th gen) render (near-identical
  // design); the all-screen Air 4 reuses the iPad Air (M1) render.
  {
    id: "ipad8",
    slug: "ipad-8th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (8th gen)",
    line: "iPad",
    releaseYear: 2020,
    modelNumbers: "A2270 / A2428",
    chip: "A12 Bionic",
    screen: 10.2,
    ram: 3,
    image: "/photos/ipad-8th-gen.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 32, price: 169, original: 329, wholesale: 153 },
      { gb: 128, price: 229, original: 429, wholesale: 208 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 46,
    stock: 351,
    badge: "Budget pick",
    features: ["A12 Bionic", '10.2" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "A12 Bionic keeps everyday apps fast",
      'Roomy 10.2" Retina display',
      "Works with Apple Pencil and Smart Keyboard",
    ],
  },
  {
    id: "ipad7",
    slug: "ipad-7th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (7th gen)",
    line: "iPad",
    releaseYear: 2019,
    modelNumbers: "A2197 / A2200",
    chip: "A10 Fusion",
    screen: 10.2,
    ram: 3,
    image: "/photos/ipad-7th-gen.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 32, price: 149, original: 329, wholesale: 135 },
      { gb: 128, price: 199, original: 429, wholesale: 181 },
    ],
    grade: "good",
    batteryHealth: 89,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.5,
    reviews: 87,
    stock: 1370,
    badge: "Best value",
    features: ["A10 Fusion", '10.2" Retina', "Touch ID", "Smart Connector"],
    highlights: [
      "The most affordable full-size iPad we stock",
      "Plenty of power for browsing, video and notes",
      "Smart Connector for full-size keyboards",
    ],
  },
  {
    id: "ipad6",
    slug: "ipad-6th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (6th gen)",
    line: "iPad",
    releaseYear: 2018,
    modelNumbers: "A1893 / A1954",
    chip: "A10 Fusion",
    screen: 9.7,
    ram: 2,
    image: "/photos/ipad-6th-gen.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 32, price: 129, original: 329, wholesale: 117 },
      { gb: 128, price: 169, original: 429, wholesale: 153 },
    ],
    grade: "good",
    batteryHealth: 88,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.5,
    reviews: 59,
    stock: 419,
    features: ["A10 Fusion", '9.7" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "First budget iPad with Apple Pencil support",
      "Compact 9.7-inch Retina display",
      "Great reliable pick for students",
    ],
  },
  {
    id: "ipad5",
    slug: "ipad-5th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (5th gen)",
    line: "iPad",
    releaseYear: 2017,
    modelNumbers: "A1822 / A1823",
    chip: "A9",
    screen: 9.7,
    ram: 2,
    image: "/photos/ipad-5th-gen.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 32, price: 109, original: 329, wholesale: 99 },
      { gb: 128, price: 149, original: 429, wholesale: 135 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.4,
    reviews: 41,
    stock: 239,
    features: ["A9 chip", '9.7" Retina', "Touch ID", "10-hour battery"],
    highlights: [
      "Wallet-friendly way into iPadOS",
      "Solid for web, email and streaming",
      "Lightweight 9.7-inch design",
    ],
  },
  {
    id: "ipadair4",
    slug: "ipad-air-4",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air (4th gen)",
    line: "iPad Air",
    releaseYear: 2020,
    modelNumbers: "A2316 / A2324",
    chip: "A14 Bionic",
    screen: 10.9,
    ram: 4,
    image: "/photos/ipad-air-4.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Rose Gold", hex: "#ecc8bf", accent: "#d3a596", family: "Pink" },
      { name: "Green", hex: "#cfe0cd", accent: "#a7c4a3", family: "Green" },
      { name: "Sky Blue", hex: "#cfe0e8", accent: "#a3c4d2", family: "Blue" },
    ],
    storage: [
      { gb: 64, price: 319, original: 599, wholesale: 290 },
      { gb: 256, price: 419, original: 749, wholesale: 381 },
    ],
    grade: "excellent",
    batteryHealth: 92,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.7,
    reviews: 38,
    stock: 52,
    badge: "All-screen",
    features: ["A14 Bionic", '10.9" Liquid Retina', "USB-C", "Apple Pencil 2"],
    highlights: [
      "First all-screen Air with Touch ID in the top button",
      "A14 Bionic handles demanding apps with ease",
      "USB-C and Apple Pencil 2 support",
    ],
  },
  {
    id: "ipadair3",
    slug: "ipad-air-3",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air (3rd gen)",
    line: "iPad Air",
    releaseYear: 2019,
    modelNumbers: "A2152 / A2153",
    chip: "A12 Bionic",
    screen: 10.5,
    ram: 3,
    image: "/renders/ipad-9th-gen.png",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 215, original: 499, wholesale: 195 },
      { gb: 256, price: 289, original: 649, wholesale: 263 },
    ],
    grade: "good",
    batteryHealth: 90,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 31,
    stock: 52,
    features: ["A12 Bionic", '10.5" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "Laminated 10.5-inch Retina display",
      "A12 Bionic keeps up with modern apps",
      "Smart Keyboard and Apple Pencil support",
    ],
  },
  {
    id: "ipadair2",
    slug: "ipad-air-2",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air 2",
    line: "iPad Air",
    releaseYear: 2014,
    modelNumbers: "A1566 / A1567",
    chip: "A8X",
    screen: 9.7,
    ram: 2,
    image: "/photos/ipad-air-2.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 16, price: 99, original: 499, wholesale: 90 },
      { gb: 32, price: 115, original: 549, wholesale: 104 },
      { gb: 64, price: 129, original: 599, wholesale: 117 },
      { gb: 128, price: 155, original: 699, wholesale: 141 },
    ],
    grade: "fair",
    batteryHealth: 85,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.3,
    reviews: 33,
    stock: 206,
    features: ["A8X chip", '9.7" Retina', "Touch ID", "Ultra-thin design"],
    highlights: [
      "Famously thin and light aluminium design",
      "Reliable for browsing, reading and video",
      "Budget-friendly entry to the Air line",
    ],
  },
  {
    id: "ipadair1",
    slug: "ipad-air",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air",
    line: "iPad Air",
    releaseYear: 2013,
    modelNumbers: "A1474 / A1475",
    chip: "A7",
    screen: 9.7,
    ram: 1,
    image: "/renders/ipad-9th-gen.png",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
    ],
    storage: [
      { gb: 16, price: 75, original: 499, wholesale: 68 },
      { gb: 32, price: 87, original: 549, wholesale: 79 },
      { gb: 64, price: 99, original: 599, wholesale: 90 },
    ],
    grade: "fair",
    batteryHealth: 84,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.2,
    reviews: 20,
    stock: 30,
    features: ["A7 chip", '9.7" Retina', "Touch-free Home", "10-hour battery"],
    highlights: [
      "The original ultra-light iPad Air",
      "Great value secondary tablet for the home",
      "Handles reading, web and video happily",
    ],
  },
  {
    id: "ipadmini5",
    slug: "ipad-mini-5",
    brand: "Apple",
    type: "tablet",
    name: "iPad mini (5th gen)",
    line: "iPad mini",
    releaseYear: 2019,
    modelNumbers: "A2133 / A2126",
    chip: "A12 Bionic",
    screen: 7.9,
    ram: 3,
    image: "/photos/ipad-mini-5.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 219, original: 399, wholesale: 199 },
      { gb: 256, price: 289, original: 549, wholesale: 263 },
    ],
    grade: "good",
    batteryHealth: 90,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.7,
    reviews: 37,
    stock: 101,
    badge: "Compact",
    features: ["A12 Bionic", '7.9" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "Pocketable power with A12 Bionic",
      "Best small iPad for reading and notes",
      "Apple Pencil 1 support",
    ],
  },
  {
    id: "ipadmini4",
    slug: "ipad-mini-4",
    brand: "Apple",
    type: "tablet",
    name: "iPad mini 4",
    line: "iPad mini",
    releaseYear: 2015,
    modelNumbers: "A1538 / A1550",
    chip: "A8",
    screen: 7.9,
    ram: 2,
    image: "/photos/ipad-mini-4.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
    ],
    storage: [
      { gb: 16, price: 105, original: 399, wholesale: 95 },
      { gb: 32, price: 119, original: 449, wholesale: 108 },
      { gb: 128, price: 149, original: 549, wholesale: 135 },
    ],
    grade: "fair",
    batteryHealth: 85,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.3,
    reviews: 25,
    stock: 78,
    features: ["A8 chip", '7.9" Retina', "Touch ID", "Ultra-compact"],
    highlights: [
      "Tiny, light and easy to hold one-handed",
      "Ideal cheap tablet for kids and reading",
      "Retina display in a pocketable size",
    ],
  },
  {
    id: "ipadpro105",
    slug: "ipad-pro-10-5",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 10.5"',
    line: "iPad Pro",
    releaseYear: 2017,
    modelNumbers: "A1701 / A1709",
    chip: "A10X Fusion",
    screen: 10.5,
    ram: 4,
    image: "/renders/ipad-9th-gen.png",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
      { name: "Rose Gold", hex: "#ecc8bf", accent: "#d3a596", family: "Pink" },
    ],
    storage: [
      { gb: 64, price: 209, original: 649, wholesale: 190 },
      { gb: 256, price: 269, original: 799, wholesale: 245 },
      { gb: 512, price: 325, original: 999, wholesale: 295 },
    ],
    grade: "good",
    batteryHealth: 88,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 27,
    stock: 65,
    features: ["A10X Fusion", '10.5" ProMotion', "Apple Pencil 1", "Quad speakers"],
    highlights: [
      "120Hz ProMotion display, still buttery today",
      "Four-speaker audio for movies and music",
      "Plenty of power for Pencil note-taking",
    ],
  },
  {
    id: "ipadpro97",
    slug: "ipad-pro-9-7",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 9.7"',
    line: "iPad Pro",
    releaseYear: 2016,
    modelNumbers: "A1673 / A1674",
    chip: "A9X",
    screen: 9.7,
    ram: 2,
    image: "/renders/ipad-9th-gen.png",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#e6d2b5", accent: "#cdb389", family: "Gold" },
      { name: "Rose Gold", hex: "#ecc8bf", accent: "#d3a596", family: "Pink" },
    ],
    storage: [
      { gb: 32, price: 159, original: 599, wholesale: 145 },
      { gb: 128, price: 199, original: 749, wholesale: 181 },
      { gb: 256, price: 235, original: 899, wholesale: 214 },
    ],
    grade: "fair",
    batteryHealth: 86,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.4,
    reviews: 22,
    stock: 183,
    features: ["A9X chip", '9.7" Retina', "Apple Pencil 1", "Quad speakers"],
    highlights: [
      "The first 9.7-inch iPad Pro with Pencil support",
      "True Tone display and four-speaker audio",
      "Compact Pro for notes and sketching",
    ],
  },
  {
    id: "ipadpro129",
    slug: "ipad-pro-12-9",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 12.9" (2020)',
    line: "iPad Pro",
    releaseYear: 2020,
    modelNumbers: "A2229 / A2069",
    chip: "A12Z Bionic",
    screen: 12.9,
    ram: 6,
    image: "/photos/ipad-pro-12-9.jpg",
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
    ],
    storage: [
      { gb: 128, price: 430, original: 999, wholesale: 391 },
      { gb: 256, price: 500, original: 1099, wholesale: 455 },
      { gb: 512, price: 600, original: 1299, wholesale: 546 },
      { gb: 1024, price: 720, original: 1499, wholesale: 655 },
    ],
    grade: "good",
    batteryHealth: 89,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.7,
    reviews: 20,
    stock: 58,
    badge: "Pro display",
    features: ["A12Z Bionic", '12.9" Liquid Retina', "LiDAR Scanner", "Face ID"],
    highlights: [
      "Big 12.9-inch Liquid Retina canvas for work and art",
      "LiDAR Scanner and Pro cameras",
      "Face ID and Apple Pencil 2 with USB-C",
    ],
  },
];

/** Path to the pre-rendered 3D product photo for a device (see /public/renders). */
export function renderSrc(slug: string): string {
  return `/renders/${slug}.png`;
}

export function getDevice(slug: string): Device | undefined {
  return DEVICES.find((d) => d.slug === slug);
}

export function baseStorage(d: Device): StorageOption {
  return d.storage.reduce((a, b) => (b.price < a.price ? b : a), d.storage[0]);
}

export function startingPrice(d: Device): number {
  return Math.min(...d.storage.map((s) => s.price));
}

/**
 * Lowest advertised price — Fair grade at the cheapest storage. Mirrors the
 * per-grade pricing used on the product page (each grade step is ±6%). This is
 * the "from" price shown on listing cards so one model = one listing.
 */
export function fromPrice(d: Device): number {
  const mult = 1 + (GRADES.fair.score - GRADES[d.grade].score) * 0.06;
  return Math.round(startingPrice(d) * mult);
}

/**
 * Best real photo for a slug (+ optional colour) — used for cart, search and
 * order thumbnails so they show the actual product photo, not a render.
 */
export function imageFor(slug: string | undefined, colorName?: string): string | undefined {
  if (!slug) return undefined;
  const d = getDevice(slug);
  if (!d) return undefined;
  if (colorName) {
    const c = d.colors.find((x) => x.name === colorName);
    if (c?.image) return c.image;
  }
  return d.image ?? d.colors.find((x) => x.image)?.image;
}

export function storageFor(d: Device, gb: number): StorageOption {
  return d.storage.find((s) => s.gb === gb) ?? baseStorage(d);
}

export function defaultColor(d: Device): Colorway {
  return d.colors[0];
}

export function bestDiscount(d: Device): number {
  return Math.max(
    ...d.storage.map((s) => (s.original > 0 ? Math.round((1 - s.price / s.original) * 100) : 0)),
  );
}

/**
 * Devices that actually have warehouse stock — the storefront only lists
 * these. A missing/empty stock map (feed unavailable) fails open to the full
 * catalog so the shop can never render empty by accident.
 */
export function stockedDevices(stock: Record<string, number> | null | undefined): Device[] {
  if (!stock || Object.keys(stock).length === 0) return DEVICES;
  const visible = DEVICES.filter((d) => (stock[d.slug] ?? 0) > 0);
  return visible.length > 0 ? visible : DEVICES;
}

export function popularDevices(): Device[] {
  return DEVICES.filter((d) => d.popular);
}

export function devicesOfType(type: DeviceType): Device[] {
  return DEVICES.filter((d) => d.type === type);
}

export function relatedDevices(device: Device, count = 4): Device[] {
  return DEVICES.filter((d) => d.id !== device.id)
    .map((d) => {
      let score = 0;
      if (d.type === device.type) score += 2;
      if (d.brand === device.brand) score += 1;
      if (d.line === device.line) score += 2;
      if (Math.abs(startingPrice(d) - startingPrice(device)) < 200) score += 1;
      return { d, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, count)
    .map((x) => x.d);
}

// ---- derived spec strings (grounded in existing fields; no fabricated data) -

const CAMERA_COUNT: Record<CameraLayout, string> = {
  triple: "Triple",
  dual: "Dual",
  single: "Single",
  vertical: "Triple",
  grid: "Quad",
  bar: "Dual",
  circular: "Dual",
};

/** Display panel description, e.g. `6.1" Super Retina XDR OLED`. */
export function displaySpec(d: Device): string {
  const panel =
    d.brand === "Apple"
      ? d.type === "tablet"
        ? "Liquid Retina"
        : "Super Retina XDR OLED"
      : d.type === "tablet"
        ? "Touchscreen LCD"
        : "Dynamic AMOLED";
  return `${d.screen}" ${panel}`;
}

/** Rear-camera summary, reusing the catalog's own feature copy when it names MP. */
export function rearCameraSpec(d: Device): string {
  const mp = d.features.find((f) => /\d\s?MP/i.test(f));
  const count = CAMERA_COUNT[d.cameraLayout] ?? "Multi";
  if (d.type === "tablet") return mp ?? "12MP Wide";
  return mp ? `${count} · ${mp}` : `${count} camera`;
}

/** Front-camera summary. */
export function frontCameraSpec(d: Device): string {
  return d.brand === "Apple" ? "12MP TrueDepth · Face ID" : "Selfie camera";
}

/** Ingress-protection rating, derived from line/type. */
export function waterResistance(d: Device): string {
  if (d.type === "tablet") return "Not rated";
  if (d.line.includes("SE")) return "IP67";
  if (/Galaxy A/.test(d.name)) return "IP67";
  if (/Z Flip|Z Fold/.test(d.name)) return "IPX8";
  return "IP68";
}

/** SIM support. */
export function simType(d: Device): string {
  if (d.type === "tablet") return d.cellular ? "Nano-SIM + eSIM" : "Wi-Fi only";
  return "Nano-SIM + eSIM";
}

/** Slugify a colour name → filename token, e.g. "Space Gray" → "space-gray". */
export function colorSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

// Wire per-colour product photos from public/photos. color-photos.json holds
// the "<slug>::<colorSlug>" keys that actually have a file on disk, so a colour
// only points at a photo when one exists (otherwise it falls back to the render).
const COLOR_PHOTO_SET = new Set(colorPhotos as string[]);
for (const d of DEVICES) {
  let firstPhoto: string | undefined;
  for (const c of d.colors) {
    if (COLOR_PHOTO_SET.has(`${d.slug}::${colorSlug(c.name)}`)) {
      c.image = `/photos/${d.slug}__${colorSlug(c.name)}.jpg`;
      if (!firstPhoto) firstPhoto = c.image;
    }
  }
  if (firstPhoto && !d.image) d.image = firstPhoto;
}
