import type { GradeId } from "./grades";

export type Brand =
  | "Apple"
  | "Samsung"
  | "Google"
  | "OnePlus"
  | "Xiaomi"
  | "Nothing";

export type CameraLayout =
  | "triple" // square bump, 3 lenses (iPhone Pro)
  | "dual" // 2 lenses diagonal
  | "single"
  | "vertical" // stacked (Galaxy S)
  | "grid" // 2x2 (Ultra / budget)
  | "bar" // horizontal visor (Pixel)
  | "circular"; // round island (OnePlus)

export interface Phone {
  id: string;
  slug: string;
  brand: Brand;
  name: string;
  color: string;
  /** body color for the 3D model + swatch */
  colorHex: string;
  /** accent for camera rings / rails */
  accentHex: string;
  storage: number; // GB
  ram: number; // GB
  grade: GradeId;
  batteryHealth: number; // %
  price: number; // certified pre-owned retail price
  originalPrice: number; // launch MSRP
  wholesalePrice: number; // base unit price (tier 1, 5–24 units)
  stock: number;
  releaseYear: number;
  screen: number; // inches
  chip: string;
  rating: number; // 1..5
  reviews: number;
  carrier: string;
  cameraLayout: CameraLayout;
  fiveG: boolean;
  popular?: boolean;
  badge?: string;
  features: string[];
  highlights: string[];
}

export const PHONES: Phone[] = [
  {
    id: "ip15pm",
    slug: "iphone-15-pro-max",
    brand: "Apple",
    name: "iPhone 15 Pro Max",
    color: "Natural Titanium",
    colorHex: "#c8c2b4",
    accentHex: "#8d8a82",
    storage: 256,
    ram: 8,
    grade: "pristine",
    batteryHealth: 97,
    price: 1019,
    originalPrice: 1199,
    wholesalePrice: 939,
    stock: 42,
    releaseYear: 2023,
    screen: 6.7,
    chip: "A17 Pro",
    rating: 4.9,
    reviews: 1284,
    carrier: "Unlocked",
    cameraLayout: "triple",
    fiveG: true,
    popular: true,
    badge: "Best seller",
    features: ["5x Telephoto", "Titanium frame", "Action button", "USB-C", "120Hz ProMotion"],
    highlights: [
      "Aerospace-grade titanium body, lighter than steel",
      "A17 Pro chip handles console-grade gaming",
      "Tetraprism 5x optical zoom camera system",
    ],
  },
  {
    id: "ip15p",
    slug: "iphone-15-pro",
    brand: "Apple",
    name: "iPhone 15 Pro",
    color: "Blue Titanium",
    colorHex: "#566472",
    accentHex: "#9aa7b4",
    storage: 128,
    ram: 8,
    grade: "excellent",
    batteryHealth: 94,
    price: 829,
    originalPrice: 999,
    wholesalePrice: 759,
    stock: 67,
    releaseYear: 2023,
    screen: 6.1,
    chip: "A17 Pro",
    rating: 4.8,
    reviews: 942,
    carrier: "Unlocked",
    cameraLayout: "triple",
    fiveG: true,
    popular: true,
    features: ["3x Telephoto", "Titanium frame", "Action button", "USB-C", "120Hz ProMotion"],
    highlights: [
      "Pro camera system with 3x optical zoom",
      "Customizable Action button replaces the mute switch",
      "USB-C with USB 3 transfer speeds",
    ],
  },
  {
    id: "ip15",
    slug: "iphone-15",
    brand: "Apple",
    name: "iPhone 15",
    color: "Pink",
    colorHex: "#efccd2",
    accentHex: "#e0a9b3",
    storage: 128,
    ram: 6,
    grade: "excellent",
    batteryHealth: 93,
    price: 629,
    originalPrice: 799,
    wholesalePrice: 569,
    stock: 88,
    releaseYear: 2023,
    screen: 6.1,
    chip: "A16 Bionic",
    rating: 4.8,
    reviews: 731,
    carrier: "Unlocked",
    cameraLayout: "dual",
    fiveG: true,
    features: ["48MP main", "Dynamic Island", "USB-C", "Ceramic Shield"],
    highlights: [
      "48MP main camera with 2x telephoto crop",
      "Dynamic Island arrives on the standard model",
      "Color-infused glass back",
    ],
  },
  {
    id: "ip14p",
    slug: "iphone-14-pro",
    brand: "Apple",
    name: "iPhone 14 Pro",
    color: "Deep Purple",
    colorHex: "#5a5570",
    accentHex: "#3f3b52",
    storage: 128,
    ram: 6,
    grade: "good",
    batteryHealth: 89,
    price: 679,
    originalPrice: 999,
    wholesalePrice: 619,
    stock: 54,
    releaseYear: 2022,
    screen: 6.1,
    chip: "A16 Bionic",
    rating: 4.7,
    reviews: 1106,
    carrier: "Unlocked",
    cameraLayout: "triple",
    fiveG: true,
    badge: "Great value",
    features: ["48MP main", "Always-On display", "Dynamic Island", "ProMotion"],
    highlights: [
      "First iPhone with the Dynamic Island",
      "48MP quad-pixel sensor for sharper detail",
      "Always-On display with 1Hz refresh",
    ],
  },
  {
    id: "ip14",
    slug: "iphone-14",
    brand: "Apple",
    name: "iPhone 14",
    color: "Midnight",
    colorHex: "#22252f",
    accentHex: "#3a3d47",
    storage: 128,
    ram: 6,
    grade: "excellent",
    batteryHealth: 91,
    price: 499,
    originalPrice: 799,
    wholesalePrice: 449,
    stock: 73,
    releaseYear: 2022,
    screen: 6.1,
    chip: "A15 Bionic",
    rating: 4.7,
    reviews: 658,
    carrier: "Unlocked",
    cameraLayout: "dual",
    fiveG: true,
    features: ["Dual 12MP", "Crash Detection", "Photonic Engine"],
    highlights: [
      "Photonic Engine boosts low-light photography",
      "Crash Detection and Emergency SOS",
      "All-day battery on the efficient A15",
    ],
  },
  {
    id: "ip13",
    slug: "iphone-13",
    brand: "Apple",
    name: "iPhone 13",
    color: "Starlight",
    colorHex: "#f3efe6",
    accentHex: "#d9d3c4",
    storage: 128,
    ram: 4,
    grade: "good",
    batteryHealth: 87,
    price: 389,
    originalPrice: 699,
    wholesalePrice: 349,
    stock: 96,
    releaseYear: 2021,
    screen: 6.1,
    chip: "A15 Bionic",
    rating: 4.6,
    reviews: 1442,
    carrier: "Unlocked",
    cameraLayout: "dual",
    fiveG: true,
    popular: true,
    features: ["Dual 12MP", "Cinematic mode", "Super Retina XDR"],
    highlights: [
      "The value champion of the lineup",
      "Cinematic mode for depth-of-field video",
      "Still receiving the latest iOS updates",
    ],
  },
  {
    id: "ipse3",
    slug: "iphone-se-2022",
    brand: "Apple",
    name: "iPhone SE (2022)",
    color: "Midnight",
    colorHex: "#1f222b",
    accentHex: "#34373f",
    storage: 64,
    ram: 4,
    grade: "fair",
    batteryHealth: 84,
    price: 159,
    originalPrice: 429,
    wholesalePrice: 139,
    stock: 120,
    releaseYear: 2022,
    screen: 4.7,
    chip: "A15 Bionic",
    rating: 4.4,
    reviews: 503,
    carrier: "Unlocked",
    cameraLayout: "single",
    fiveG: true,
    badge: "Budget pick",
    features: ["Touch ID", "A15 chip", "5G", "Compact"],
    highlights: [
      "Flagship A15 chip in a compact, affordable body",
      "Classic Touch ID home button",
      "Ideal fleet and starter device",
    ],
  },
  {
    id: "s24u",
    slug: "galaxy-s24-ultra",
    brand: "Samsung",
    name: "Galaxy S24 Ultra",
    color: "Titanium Gray",
    colorHex: "#6c7077",
    accentHex: "#42454b",
    storage: 256,
    ram: 12,
    grade: "pristine",
    batteryHealth: 96,
    price: 939,
    originalPrice: 1299,
    wholesalePrice: 869,
    stock: 38,
    releaseYear: 2024,
    screen: 6.8,
    chip: "Snapdragon 8 Gen 3",
    rating: 4.9,
    reviews: 877,
    carrier: "Unlocked",
    cameraLayout: "grid",
    fiveG: true,
    popular: true,
    badge: "AI flagship",
    features: ["200MP camera", "S Pen", "Titanium frame", "Galaxy AI", "5x Periscope"],
    highlights: [
      "200MP sensor with dual telephoto reach",
      "Built-in S Pen and titanium frame",
      "Galaxy AI: live translate, circle to search",
    ],
  },
  {
    id: "s24",
    slug: "galaxy-s24",
    brand: "Samsung",
    name: "Galaxy S24",
    color: "Cobalt Violet",
    colorHex: "#8a7fc4",
    accentHex: "#5d5391",
    storage: 128,
    ram: 8,
    grade: "excellent",
    batteryHealth: 95,
    price: 599,
    originalPrice: 799,
    wholesalePrice: 549,
    stock: 61,
    releaseYear: 2024,
    screen: 6.2,
    chip: "Snapdragon 8 Gen 3",
    rating: 4.8,
    reviews: 412,
    carrier: "Unlocked",
    cameraLayout: "vertical",
    fiveG: true,
    features: ["Galaxy AI", "120Hz", "Triple camera", "Compact flagship"],
    highlights: [
      "Full Galaxy AI suite in a pocketable size",
      "Brilliant 2600-nit adaptive display",
      "Seven years of OS updates promised",
    ],
  },
  {
    id: "s23",
    slug: "galaxy-s23",
    brand: "Samsung",
    name: "Galaxy S23",
    color: "Phantom Black",
    colorHex: "#191b20",
    accentHex: "#2c2f36",
    storage: 128,
    ram: 8,
    grade: "good",
    batteryHealth: 88,
    price: 449,
    originalPrice: 799,
    wholesalePrice: 409,
    stock: 70,
    releaseYear: 2023,
    screen: 6.1,
    chip: "Snapdragon 8 Gen 2",
    rating: 4.7,
    reviews: 988,
    carrier: "Unlocked",
    cameraLayout: "vertical",
    fiveG: true,
    features: ["50MP triple", "120Hz", "Snapdragon for Galaxy"],
    highlights: [
      "Compact powerhouse with all-day battery",
      "50MP triple camera with 3x optical zoom",
      "Still a current-gen flagship experience",
    ],
  },
  {
    id: "zflip5",
    slug: "galaxy-z-flip5",
    brand: "Samsung",
    name: "Galaxy Z Flip5",
    color: "Mint",
    colorHex: "#bfe6d2",
    accentHex: "#8fcbb0",
    storage: 256,
    ram: 8,
    grade: "excellent",
    batteryHealth: 92,
    price: 649,
    originalPrice: 999,
    wholesalePrice: 589,
    stock: 29,
    releaseYear: 2023,
    screen: 6.7,
    chip: "Snapdragon 8 Gen 2",
    rating: 4.6,
    reviews: 334,
    carrier: "Unlocked",
    cameraLayout: "dual",
    fiveG: true,
    badge: "Foldable",
    features: ["Flex Window", "Foldable", "3.4in cover screen", "IPX8"],
    highlights: [
      "Large 3.4-inch Flex Window cover display",
      "Folds flat into a true pocket size",
      "Hands-free FlexCam photography",
    ],
  },
  {
    id: "a54",
    slug: "galaxy-a54-5g",
    brand: "Samsung",
    name: "Galaxy A54 5G",
    color: "Awesome Lime",
    colorHex: "#c4e36a",
    accentHex: "#9bbb46",
    storage: 128,
    ram: 8,
    grade: "good",
    batteryHealth: 90,
    price: 269,
    originalPrice: 449,
    wholesalePrice: 239,
    stock: 134,
    releaseYear: 2023,
    screen: 6.4,
    chip: "Exynos 1380",
    rating: 4.5,
    reviews: 760,
    carrier: "Unlocked",
    cameraLayout: "grid",
    fiveG: true,
    badge: "Fleet favorite",
    features: ["50MP OIS", "5000mAh", "120Hz", "IP67"],
    highlights: [
      "Huge 5000mAh battery for two-day use",
      "Premium glass design at a mid-range price",
      "Best-value device for bulk deployments",
    ],
  },
  {
    id: "px8p",
    slug: "pixel-8-pro",
    brand: "Google",
    name: "Pixel 8 Pro",
    color: "Bay Blue",
    colorHex: "#3f6fa8",
    accentHex: "#274a73",
    storage: 128,
    ram: 12,
    grade: "excellent",
    batteryHealth: 94,
    price: 619,
    originalPrice: 999,
    wholesalePrice: 559,
    stock: 47,
    releaseYear: 2023,
    screen: 6.7,
    chip: "Tensor G3",
    rating: 4.8,
    reviews: 521,
    carrier: "Unlocked",
    cameraLayout: "bar",
    fiveG: true,
    popular: true,
    badge: "Best camera",
    features: ["50MP triple", "7yr updates", "Magic Editor", "Temp sensor"],
    highlights: [
      "Best-in-class computational photography",
      "Seven years of OS and security updates",
      "AI Magic Editor and Best Take built in",
    ],
  },
  {
    id: "px8",
    slug: "pixel-8",
    brand: "Google",
    name: "Pixel 8",
    color: "Hazel",
    colorHex: "#8f8a7a",
    accentHex: "#65604f",
    storage: 128,
    ram: 8,
    grade: "good",
    batteryHealth: 89,
    price: 429,
    originalPrice: 699,
    wholesalePrice: 389,
    stock: 82,
    releaseYear: 2023,
    screen: 6.2,
    chip: "Tensor G3",
    rating: 4.7,
    reviews: 643,
    carrier: "Unlocked",
    cameraLayout: "bar",
    fiveG: true,
    features: ["50MP main", "Actua display", "7yr updates", "Face Unlock"],
    highlights: [
      "Compact body with a vivid 120Hz Actua display",
      "Google Tensor G3 with on-device AI",
      "Guaranteed updates through 2030",
    ],
  },
  {
    id: "px7",
    slug: "pixel-7",
    brand: "Google",
    name: "Pixel 7",
    color: "Snow",
    colorHex: "#f3f2ee",
    accentHex: "#cfcdc6",
    storage: 128,
    ram: 8,
    grade: "fair",
    batteryHealth: 85,
    price: 289,
    originalPrice: 599,
    wholesalePrice: 259,
    stock: 91,
    releaseYear: 2022,
    screen: 6.3,
    chip: "Tensor G2",
    rating: 4.5,
    reviews: 1029,
    carrier: "Unlocked",
    cameraLayout: "bar",
    fiveG: true,
    features: ["50MP dual", "Magic Eraser", "Face Unlock"],
    highlights: [
      "Iconic Pixel camera bar design",
      "Magic Eraser and Photo Unblur",
      "Outstanding photos for the price",
    ],
  },
  {
    id: "op12",
    slug: "oneplus-12",
    brand: "OnePlus",
    name: "OnePlus 12",
    color: "Flowy Emerald",
    colorHex: "#1f6b52",
    accentHex: "#0f4733",
    storage: 256,
    ram: 12,
    grade: "excellent",
    batteryHealth: 95,
    price: 599,
    originalPrice: 799,
    wholesalePrice: 549,
    stock: 44,
    releaseYear: 2024,
    screen: 6.82,
    chip: "Snapdragon 8 Gen 3",
    rating: 4.7,
    reviews: 388,
    carrier: "Unlocked",
    cameraLayout: "circular",
    fiveG: true,
    badge: "Fast charge",
    features: ["100W charging", "Hasselblad", "5400mAh", "120Hz LTPO"],
    highlights: [
      "100W charging — full in under 30 minutes",
      "Hasselblad-tuned triple camera",
      "Massive 5400mAh silicon-carbon battery",
    ],
  },
  {
    id: "xm14",
    slug: "xiaomi-14",
    brand: "Xiaomi",
    name: "Xiaomi 14",
    color: "Jade Green",
    colorHex: "#2f7d62",
    accentHex: "#1c5141",
    storage: 256,
    ram: 12,
    grade: "good",
    batteryHealth: 91,
    price: 469,
    originalPrice: 799,
    wholesalePrice: 429,
    stock: 58,
    releaseYear: 2024,
    screen: 6.36,
    chip: "Snapdragon 8 Gen 3",
    rating: 4.6,
    reviews: 276,
    carrier: "Unlocked",
    cameraLayout: "grid",
    fiveG: true,
    features: ["Leica optics", "90W charging", "1.5K display", "IP68"],
    highlights: [
      "Leica Summilux triple camera system",
      "Compact flagship with a 1.5K LTPO screen",
      "90W wired and 50W wireless charging",
    ],
  },
  {
    id: "np2",
    slug: "nothing-phone-2",
    brand: "Nothing",
    name: "Nothing Phone (2)",
    color: "Dark Gray",
    colorHex: "#2a2c30",
    accentHex: "#46484d",
    storage: 256,
    ram: 12,
    grade: "excellent",
    batteryHealth: 93,
    price: 399,
    originalPrice: 599,
    wholesalePrice: 359,
    stock: 51,
    releaseYear: 2023,
    screen: 6.7,
    chip: "Snapdragon 8+ Gen 1",
    rating: 4.6,
    reviews: 415,
    carrier: "Unlocked",
    cameraLayout: "dual",
    fiveG: true,
    badge: "Glyph design",
    features: ["Glyph Interface", "Nothing OS", "Dual 50MP", "120Hz LTPO"],
    highlights: [
      "Iconic Glyph LED interface on the back",
      "Clean, fast Nothing OS experience",
      "Transparent design that stands out",
    ],
  },
];

export const BRANDS: Brand[] = ["Apple", "Samsung", "Google", "OnePlus", "Xiaomi", "Nothing"];

export const STORAGE_OPTIONS = [64, 128, 256] as const;

export function getPhone(slug: string): Phone | undefined {
  return PHONES.find((p) => p.slug === slug);
}

export function relatedPhones(phone: Phone, count = 3): Phone[] {
  return PHONES.filter((p) => p.id !== phone.id)
    .sort((a, b) => {
      const aScore = (a.brand === phone.brand ? 2 : 0) + (Math.abs(a.price - phone.price) < 200 ? 1 : 0);
      const bScore = (b.brand === phone.brand ? 2 : 0) + (Math.abs(b.price - phone.price) < 200 ? 1 : 0);
      return bScore - aScore;
    })
    .slice(0, count);
}

export function popularPhones(): Phone[] {
  return PHONES.filter((p) => p.popular);
}
