import type { GradeId } from "./grades";

export type Brand = "Apple" | "Samsung";
export type DeviceType = "phone" | "tablet";
export type CameraLayout =
  | "triple"
  | "dual"
  | "single"
  | "vertical"
  | "grid"
  | "bar"
  | "circular";

export type ColorFamily =
  | "Black"
  | "Gray"
  | "Silver"
  | "White"
  | "Gold"
  | "Blue"
  | "Green"
  | "Purple"
  | "Pink"
  | "Red"
  | "Yellow"
  | "Titanium";

export interface Colorway {
  name: string;
  hex: string;
  accent: string;
  family: ColorFamily;
}

export interface StorageOption {
  gb: number;
  price: number;
  original: number;
  wholesale: number;
}

export interface Device {
  id: string;
  slug: string;
  brand: Brand;
  type: DeviceType;
  name: string;
  line: string;
  releaseYear: number;
  chip: string;
  screen: number;
  ram: number;
  colors: Colorway[];
  storage: StorageOption[];
  grade: GradeId;
  batteryHealth: number;
  cameraLayout: CameraLayout;
  fiveG: boolean;
  cellular?: boolean;
  rating: number;
  reviews: number;
  stock: number;
  popular?: boolean;
  badge?: string;
  features: string[];
  highlights: string[];
  image?: string;
}

export const BRANDS: Brand[] = ["Apple", "Samsung"];
export const DEVICE_TYPES: DeviceType[] = ["phone", "tablet"];
export const COLOR_FAMILIES: ColorFamily[] = [
  "Black",
  "Gray",
  "Silver",
  "White",
  "Titanium",
  "Gold",
  "Blue",
  "Green",
  "Purple",
  "Pink",
  "Red",
  "Yellow",
];

export const DEVICES: Device[] = [
  {
    id: "ip11",
    slug: "iphone-11",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11",
    line: "iPhone 11",
    releaseYear: 2019,
    chip: "A13 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Black", hex: "#1d1d1f", accent: "#3a3a3c", family: "Black" },
      { name: "White", hex: "#f5f5f0", accent: "#d8d8d2", family: "White" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
      { name: "Yellow", hex: "#f6d860", accent: "#d8b945", family: "Yellow" },
      { name: "Purple", hex: "#d6c8e8", accent: "#b3a3cc", family: "Purple" },
      { name: "Green", hex: "#c9e3c5", accent: "#a3c79e", family: "Green" },
    ],
    storage: [
      { gb: 64, price: 219, original: 699, wholesale: 199 },
      { gb: 128, price: 259, original: 749, wholesale: 236 },
      { gb: 256, price: 299, original: 849, wholesale: 272 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "dual",
    fiveG: false,
    rating: 4.6,
    reviews: 2087,
    stock: 142,
    popular: true,
    badge: "Best seller",
    features: ["Dual 12MP", "Liquid Retina", "A13 Bionic", "Face ID"],
    highlights: [
      "Unbeatable everyday value pick",
      "All-day battery and Night mode photos",
      "Six fun colors to choose from",
    ],
  },
  {
    id: "ip11pro",
    slug: "iphone-11-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11 Pro",
    line: "iPhone 11",
    releaseYear: 2019,
    chip: "A13 Bionic",
    screen: 5.8,
    ram: 4,
    colors: [
      { name: "Midnight Green", hex: "#4e5851", accent: "#3a423d", family: "Green" },
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#f7e8cf", accent: "#e0c9a3", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 269, original: 999, wholesale: 245 },
      { gb: 256, price: 319, original: 1149, wholesale: 290 },
      { gb: 512, price: 369, original: 1349, wholesale: 336 },
    ],
    grade: "good",
    batteryHealth: 85,
    cameraLayout: "triple",
    fiveG: false,
    rating: 4.6,
    reviews: 1218,
    stock: 78,
    features: ["Triple 12MP", "Super Retina XDR", "A13 Bionic", "Night mode"],
    highlights: [
      "First Pro triple-camera system",
      "Gorgeous OLED Super Retina XDR display",
      "Premium stainless steel frame",
    ],
  },
  {
    id: "ip11pm",
    slug: "iphone-11-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 11 Pro Max",
    line: "iPhone 11",
    releaseYear: 2019,
    chip: "A13 Bionic",
    screen: 6.5,
    ram: 4,
    colors: [
      { name: "Midnight Green", hex: "#4e5851", accent: "#3a423d", family: "Green" },
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
      { name: "Gold", hex: "#f7e8cf", accent: "#e0c9a3", family: "Gold" },
    ],
    storage: [
      { gb: 64, price: 309, original: 1099, wholesale: 281 },
      { gb: 256, price: 369, original: 1249, wholesale: 336 },
      { gb: 512, price: 429, original: 1449, wholesale: 390 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "triple",
    fiveG: false,
    rating: 4.7,
    reviews: 1563,
    stock: 64,
    features: ["Triple 12MP", '6.5" OLED', "A13 Bionic", "Best battery"],
    highlights: [
      "Largest, brightest display of its era",
      "Exceptional battery longevity",
      "Pro triple-camera versatility",
    ],
  },
  {
    id: "ip12mini",
    slug: "iphone-12-mini",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 mini",
    line: "iPhone 12",
    releaseYear: 2020,
    chip: "A14 Bionic",
    screen: 5.4,
    ram: 4,
    colors: [
      { name: "Black", hex: "#26282b", accent: "#3f4145", family: "Black" },
      { name: "White", hex: "#f6f6f1", accent: "#d9d9d3", family: "White" },
      { name: "Red", hex: "#c1283a", accent: "#931e2c", family: "Red" },
      { name: "Green", hex: "#a7c3a0", accent: "#84a07d", family: "Green" },
      { name: "Blue", hex: "#2b4a73", accent: "#436a99", family: "Blue" },
    ],
    storage: [
      { gb: 64, price: 249, original: 699, wholesale: 227 },
      { gb: 128, price: 289, original: 749, wholesale: 263 },
      { gb: 256, price: 339, original: 849, wholesale: 308 },
    ],
    grade: "good",
    batteryHealth: 84,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.5,
    reviews: 642,
    stock: 41,
    features: ["Dual 12MP", '5.4" OLED', "A14 Bionic", "5G"],
    highlights: [
      "The most compact 5G iPhone",
      "Full flagship power in one hand",
      "Ceramic Shield front protection",
    ],
  },
  {
    id: "ip12",
    slug: "iphone-12",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12",
    line: "iPhone 12",
    releaseYear: 2020,
    chip: "A14 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Black", hex: "#26282b", accent: "#3f4145", family: "Black" },
      { name: "White", hex: "#f6f6f1", accent: "#d9d9d3", family: "White" },
      { name: "Red", hex: "#c1283a", accent: "#931e2c", family: "Red" },
      { name: "Green", hex: "#a7c3a0", accent: "#84a07d", family: "Green" },
      { name: "Blue", hex: "#2b4a73", accent: "#436a99", family: "Blue" },
      { name: "Purple", hex: "#b9b6e5", accent: "#9693c4", family: "Purple" },
    ],
    storage: [
      { gb: 64, price: 299, original: 799, wholesale: 272 },
      { gb: 128, price: 339, original: 849, wholesale: 308 },
      { gb: 256, price: 389, original: 949, wholesale: 354 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 1789,
    stock: 118,
    popular: true,
    badge: "Great value",
    features: ["Dual 12MP", "Super Retina XDR", "A14 Bionic", "5G"],
    highlights: [
      "The 5G workhorse that still delivers",
      "Ceramic Shield and OLED display",
      "Compact, flat-edge design",
    ],
  },
  {
    id: "ip12pro",
    slug: "iphone-12-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 Pro",
    line: "iPhone 12",
    releaseYear: 2020,
    chip: "A14 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Pacific Blue", hex: "#42637e", accent: "#314b60", family: "Blue" },
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
    ],
    storage: [
      { gb: 128, price: 379, original: 999, wholesale: 345 },
      { gb: 256, price: 439, original: 1099, wholesale: 400 },
      { gb: 512, price: 509, original: 1299, wholesale: 463 },
    ],
    grade: "excellent",
    batteryHealth: 87,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.7,
    reviews: 934,
    stock: 57,
    features: ["Triple 12MP", "LiDAR scanner", "Super Retina XDR", "5G"],
    highlights: [
      "LiDAR for fast low-light focus",
      "ProRAW photography support",
      "Stainless steel Pro design",
    ],
  },
  {
    id: "ip12pm",
    slug: "iphone-12-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 12 Pro Max",
    line: "iPhone 12",
    releaseYear: 2020,
    chip: "A14 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Pacific Blue", hex: "#42637e", accent: "#314b60", family: "Blue" },
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
    ],
    storage: [
      { gb: 128, price: 429, original: 1099, wholesale: 390 },
      { gb: 256, price: 489, original: 1199, wholesale: 445 },
      { gb: 512, price: 559, original: 1399, wholesale: 509 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1402,
    stock: 49,
    popular: true,
    features: ["Triple 12MP", "Sensor-shift OIS", '6.7" OLED', "LiDAR"],
    highlights: [
      "Largest sensor of the 12 lineup",
      "Sensor-shift stabilization for sharp shots",
      "Expansive 6.7-inch OLED canvas",
    ],
  },
  {
    id: "ip13mini",
    slug: "iphone-13-mini",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 mini",
    line: "iPhone 13",
    releaseYear: 2021,
    chip: "A15 Bionic",
    screen: 5.4,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#37618e", accent: "#5b85b3", family: "Blue" },
      { name: "Pink", hex: "#f7d6d9", accent: "#e6b3bb", family: "Pink" },
      { name: "Green", hex: "#3a4a3f", accent: "#5d7565", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 339, original: 699, wholesale: 308 },
      { gb: 256, price: 399, original: 799, wholesale: 363 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 521,
    stock: 33,
    features: ["Dual 12MP", "Cinematic mode", '5.4" OLED', "5G"],
    highlights: [
      "Big-phone performance, small footprint",
      "Improved battery over 12 mini",
      "Cinematic mode video built in",
    ],
  },
  {
    id: "ip13",
    slug: "iphone-13",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13",
    line: "iPhone 13",
    releaseYear: 2021,
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#37618e", accent: "#5b85b3", family: "Blue" },
      { name: "Pink", hex: "#f7d6d9", accent: "#e6b3bb", family: "Pink" },
      { name: "Green", hex: "#3a4a3f", accent: "#5d7565", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 389, original: 699, wholesale: 349 },
      { gb: 256, price: 449, original: 799, wholesale: 405 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 1442,
    stock: 96,
    popular: true,
    features: ["Dual 12MP", "Cinematic mode", "Super Retina XDR", "Face ID"],
    highlights: [
      "The value champion of the lineup",
      "Cinematic mode for depth-of-field video",
      "Still receiving the latest iOS updates",
    ],
  },
  {
    id: "ip13pro",
    slug: "iphone-13-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 Pro",
    line: "iPhone 13",
    releaseYear: 2021,
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Sierra Blue", hex: "#a7c5e3", accent: "#7fa3c4", family: "Blue" },
      { name: "Alpine Green", hex: "#535f4f", accent: "#3e4a3b", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 489, original: 999, wholesale: 445 },
      { gb: 256, price: 549, original: 1099, wholesale: 500 },
      { gb: 512, price: 629, original: 1299, wholesale: 572 },
    ],
    grade: "excellent",
    batteryHealth: 89,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1187,
    stock: 52,
    features: ["Triple 12MP", "ProMotion 120Hz", "ProRAW", "LiDAR"],
    highlights: [
      "First Pro with 120Hz ProMotion",
      "Macro photography and ProRes video",
      "Telephoto with 3x optical zoom",
    ],
  },
  {
    id: "ip13pm",
    slug: "iphone-13-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 13 Pro Max",
    line: "iPhone 13",
    releaseYear: 2021,
    chip: "A15 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Graphite", hex: "#52545a", accent: "#3c3e43", family: "Gray" },
      { name: "Gold", hex: "#f6e6c8", accent: "#dcc69c", family: "Gold" },
      { name: "Silver", hex: "#e6e7e3", accent: "#c4c5c1", family: "Silver" },
      { name: "Sierra Blue", hex: "#a7c5e3", accent: "#7fa3c4", family: "Blue" },
      { name: "Alpine Green", hex: "#535f4f", accent: "#3e4a3b", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 559, original: 1099, wholesale: 509 },
      { gb: 256, price: 629, original: 1199, wholesale: 572 },
      { gb: 512, price: 729, original: 1399, wholesale: 663 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1644,
    stock: 44,
    popular: true,
    badge: "Best seller",
    features: ["Triple 12MP", "ProMotion 120Hz", '6.7" OLED', "ProRes"],
    highlights: [
      "Best-in-class battery endurance",
      "120Hz ProMotion on a huge canvas",
      "Pro camera system with 3x zoom",
    ],
  },
  {
    id: "ip14",
    slug: "iphone-14",
    image: "/photos/iphone-14.jpg",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14",
    line: "iPhone 14",
    releaseYear: 2022,
    chip: "A15 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#a4c2dd", accent: "#7c9cb8", family: "Blue" },
      { name: "Purple", hex: "#d8d2e8", accent: "#b6afcc", family: "Purple" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 499, original: 799, wholesale: 454 },
      { gb: 256, price: 569, original: 899, wholesale: 518 },
      { gb: 512, price: 649, original: 1099, wholesale: 591 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 1098,
    stock: 88,
    features: ["Dual 12MP", "Crash Detection", "Super Retina XDR", "5G"],
    highlights: [
      "Crash Detection and Emergency SOS",
      "Improved main camera and Photonic Engine",
      "All-day battery with A15 efficiency",
    ],
  },
  {
    id: "ip14plus",
    slug: "iphone-14-plus",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Plus",
    line: "iPhone 14",
    releaseYear: 2022,
    chip: "A15 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#a4c2dd", accent: "#7c9cb8", family: "Blue" },
      { name: "Purple", hex: "#d8d2e8", accent: "#b6afcc", family: "Purple" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 549, original: 899, wholesale: 500 },
      { gb: 256, price: 619, original: 999, wholesale: 563 },
      { gb: 512, price: 699, original: 1199, wholesale: 636 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 612,
    stock: 47,
    features: ["Dual 12MP", '6.7" OLED', "Crash Detection", "Best battery"],
    highlights: [
      "Biggest battery in a non-Pro iPhone",
      "Large 6.7-inch Super Retina XDR",
      "Lighter than a Pro Max",
    ],
  },
  {
    id: "ip14pro",
    slug: "iphone-14-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Pro",
    line: "iPhone 14",
    releaseYear: 2022,
    chip: "A16 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Space Black", hex: "#2b2c2e", accent: "#444548", family: "Black" },
      { name: "Silver", hex: "#e8e9e5", accent: "#c6c7c3", family: "Silver" },
      { name: "Gold", hex: "#f3e2c2", accent: "#d9c293", family: "Gold" },
      { name: "Deep Purple", hex: "#574f5e", accent: "#423b48", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 649, original: 999, wholesale: 591 },
      { gb: 256, price: 719, original: 1099, wholesale: 654 },
      { gb: 512, price: 819, original: 1299, wholesale: 745 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1356,
    stock: 54,
    features: ["48MP main", "Dynamic Island", "Always-On display", "ProMotion"],
    highlights: [
      "First 48MP Pro camera sensor",
      "Dynamic Island redefines the notch",
      "Always-On display with ProMotion",
    ],
  },
  {
    id: "ip14pm",
    slug: "iphone-14-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 14 Pro Max",
    line: "iPhone 14",
    releaseYear: 2022,
    chip: "A16 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Space Black", hex: "#2b2c2e", accent: "#444548", family: "Black" },
      { name: "Silver", hex: "#e8e9e5", accent: "#c6c7c3", family: "Silver" },
      { name: "Gold", hex: "#f3e2c2", accent: "#d9c293", family: "Gold" },
      { name: "Deep Purple", hex: "#574f5e", accent: "#423b48", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 729, original: 1099, wholesale: 663 },
      { gb: 256, price: 799, original: 1199, wholesale: 727 },
      { gb: 512, price: 899, original: 1399, wholesale: 818 },
    ],
    grade: "pristine",
    batteryHealth: 92,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 1872,
    stock: 38,
    popular: true,
    badge: "Best seller",
    features: ["48MP main", "Dynamic Island", '6.7" ProMotion', "Always-On"],
    highlights: [
      "Flagship 48MP camera with 2x crop zoom",
      "Brightest, biggest Always-On display",
      "Class-leading battery life",
    ],
  },
  {
    id: "ip15",
    slug: "iphone-15",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15",
    line: "iPhone 15",
    releaseYear: 2023,
    chip: "A16 Bionic",
    screen: 6.1,
    ram: 6,
    colors: [
      { name: "Black", hex: "#3a3d40", accent: "#54575b", family: "Black" },
      { name: "Blue", hex: "#cdd9d8", accent: "#a6b4b3", family: "Blue" },
      { name: "Green", hex: "#cfd9cd", accent: "#a8b4a6", family: "Green" },
      { name: "Yellow", hex: "#f4ead0", accent: "#dccfa8", family: "Yellow" },
      { name: "Pink", hex: "#f3dde0", accent: "#dbb9bf", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 629, original: 799, wholesale: 572 },
      { gb: 256, price: 699, original: 899, wholesale: 636 },
      { gb: 512, price: 799, original: 1099, wholesale: 727 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 1241,
    stock: 92,
    popular: true,
    features: ["48MP main", "Dynamic Island", "USB-C", "5G"],
    highlights: [
      "48MP camera with 2x telephoto crop",
      "USB-C and Dynamic Island arrive",
      "Color-infused back glass",
    ],
  },
  {
    id: "ip15plus",
    slug: "iphone-15-plus",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Plus",
    line: "iPhone 15",
    releaseYear: 2023,
    chip: "A16 Bionic",
    screen: 6.7,
    ram: 6,
    colors: [
      { name: "Black", hex: "#3a3d40", accent: "#54575b", family: "Black" },
      { name: "Blue", hex: "#cdd9d8", accent: "#a6b4b3", family: "Blue" },
      { name: "Green", hex: "#cfd9cd", accent: "#a8b4a6", family: "Green" },
      { name: "Yellow", hex: "#f4ead0", accent: "#dccfa8", family: "Yellow" },
      { name: "Pink", hex: "#f3dde0", accent: "#dbb9bf", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 689, original: 899, wholesale: 627 },
      { gb: 256, price: 759, original: 999, wholesale: 691 },
      { gb: 512, price: 859, original: 1199, wholesale: 782 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 588,
    stock: 51,
    features: ["48MP main", '6.7" OLED', "USB-C", "Best battery"],
    highlights: [
      "Massive battery for two-day use",
      "Large 6.7-inch Super Retina XDR",
      "USB-C convenience at last",
    ],
  },
  {
    id: "ip15pro",
    slug: "iphone-15-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Pro",
    line: "iPhone 15",
    releaseYear: 2023,
    chip: "A17 Pro",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Natural Titanium", hex: "#b3ac9f", accent: "#928c80", family: "Titanium" },
      { name: "Blue Titanium", hex: "#56607a", accent: "#404960", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Black Titanium", hex: "#3d3d40", accent: "#56565a", family: "Titanium" },
    ],
    storage: [
      { gb: 128, price: 879, original: 999, wholesale: 800 },
      { gb: 256, price: 949, original: 1099, wholesale: 864 },
      { gb: 512, price: 1059, original: 1299, wholesale: 964 },
    ],
    grade: "pristine",
    batteryHealth: 94,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1423,
    stock: 46,
    features: ["48MP main", "A17 Pro", "Titanium", "Action button"],
    highlights: [
      "Lightweight aerospace-grade titanium",
      "A17 Pro enables console-class gaming",
      "Customizable Action button",
    ],
  },
  {
    id: "ip15pm",
    slug: "iphone-15-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 15 Pro Max",
    line: "iPhone 15",
    releaseYear: 2023,
    chip: "A17 Pro",
    screen: 6.7,
    ram: 8,
    colors: [
      { name: "Natural Titanium", hex: "#b3ac9f", accent: "#928c80", family: "Titanium" },
      { name: "Blue Titanium", hex: "#56607a", accent: "#404960", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Black Titanium", hex: "#3d3d40", accent: "#56565a", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1019, original: 1199, wholesale: 927 },
      { gb: 512, price: 1149, original: 1399, wholesale: 1046 },
      { gb: 1024, price: 1329, original: 1599, wholesale: 1209 },
    ],
    grade: "pristine",
    batteryHealth: 95,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 1934,
    stock: 31,
    popular: true,
    badge: "Best seller",
    features: ["5x Tetraprism", "A17 Pro", "Titanium", "Action button"],
    highlights: [
      "Exclusive 5x optical telephoto zoom",
      "Titanium build with the biggest battery",
      "A17 Pro for desktop-class performance",
    ],
  },
  {
    id: "ip16",
    slug: "iphone-16",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16",
    line: "iPhone 16",
    releaseYear: 2024,
    chip: "A18",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Black", hex: "#33363b", accent: "#4d5056", family: "Black" },
      { name: "White", hex: "#f1f1ec", accent: "#d2d2cd", family: "White" },
      { name: "Pink", hex: "#f4dde3", accent: "#dcb9c3", family: "Pink" },
      { name: "Teal", hex: "#a9c4c2", accent: "#82a09e", family: "Green" },
      { name: "Ultramarine", hex: "#8d9bd6", accent: "#6975b8", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 679, original: 799, wholesale: 618 },
      { gb: 256, price: 749, original: 899, wholesale: 682 },
      { gb: 512, price: 869, original: 1099, wholesale: 791 },
    ],
    grade: "pristine",
    batteryHealth: 96,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.7,
    reviews: 842,
    stock: 104,
    popular: true,
    features: ["48MP Fusion", "A18", "Camera Control", "Action button"],
    highlights: [
      "New Camera Control button for quick capture",
      "A18 chip ready for Apple Intelligence",
      "Vivid color options and durable design",
    ],
  },
  {
    id: "ip16pro",
    slug: "iphone-16-pro",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16 Pro",
    line: "iPhone 16",
    releaseYear: 2024,
    chip: "A18 Pro",
    screen: 6.3,
    ram: 8,
    colors: [
      { name: "Black Titanium", hex: "#3a3a3d", accent: "#535357", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Natural Titanium", hex: "#b6afa2", accent: "#948e82", family: "Titanium" },
      { name: "Desert Titanium", hex: "#bda47f", accent: "#9c8463", family: "Titanium" },
    ],
    storage: [
      { gb: 128, price: 899, original: 999, wholesale: 818 },
      { gb: 256, price: 969, original: 1099, wholesale: 882 },
      { gb: 512, price: 1089, original: 1299, wholesale: 991 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.8,
    reviews: 1067,
    stock: 42,
    features: ["48MP Fusion", "A18 Pro", "Camera Control", "5x zoom"],
    highlights: [
      "Larger 6.3-inch ProMotion display",
      "Pro camera with 5x telephoto and 4K120",
      "A18 Pro for advanced on-device AI",
    ],
  },
  {
    id: "ip16pm",
    slug: "iphone-16-pro-max",
    brand: "Apple",
    type: "phone",
    name: "iPhone 16 Pro Max",
    line: "iPhone 16",
    releaseYear: 2024,
    chip: "A18 Pro",
    screen: 6.9,
    ram: 8,
    colors: [
      { name: "Black Titanium", hex: "#3a3a3d", accent: "#535357", family: "Titanium" },
      { name: "White Titanium", hex: "#ecebe6", accent: "#cac9c4", family: "Titanium" },
      { name: "Natural Titanium", hex: "#b6afa2", accent: "#948e82", family: "Titanium" },
      { name: "Desert Titanium", hex: "#bda47f", accent: "#9c8463", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1059, original: 1199, wholesale: 964 },
      { gb: 512, price: 1189, original: 1399, wholesale: 1082 },
      { gb: 1024, price: 1369, original: 1599, wholesale: 1246 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "triple",
    fiveG: true,
    rating: 4.9,
    reviews: 1488,
    stock: 28,
    popular: true,
    badge: "Best seller",
    features: ["48MP Fusion", "A18 Pro", '6.9" ProMotion', "5x zoom"],
    highlights: [
      "Largest iPhone display ever at 6.9 inches",
      "Pro camera system with 4K120 ProRes",
      "Best-in-class battery and performance",
    ],
  },
  {
    id: "ipse2022",
    slug: "iphone-se-2022",
    brand: "Apple",
    type: "phone",
    name: "iPhone SE (2022)",
    line: "iPhone SE",
    releaseYear: 2022,
    chip: "A15 Bionic",
    screen: 4.7,
    ram: 4,
    colors: [
      { name: "Midnight", hex: "#22252f", accent: "#3a3d47", family: "Black" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Red", hex: "#bb2535", accent: "#8f1c28", family: "Red" },
    ],
    storage: [
      { gb: 64, price: 159, original: 429, wholesale: 145 },
      { gb: 128, price: 199, original: 479, wholesale: 181 },
      { gb: 256, price: 239, original: 579, wholesale: 218 },
    ],
    grade: "good",
    batteryHealth: 88,
    cameraLayout: "single",
    fiveG: true,
    rating: 4.4,
    reviews: 734,
    stock: 67,
    badge: "Budget pick",
    features: ["12MP single", "Touch ID", "A15 Bionic", "5G"],
    highlights: [
      "Flagship A15 chip at an entry price",
      "Classic Touch ID home button",
      "Compact and pocket-friendly",
    ],
  },
  {
    id: "s21",
    slug: "galaxy-s21",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S21",
    line: "Galaxy S21",
    releaseYear: 2021,
    chip: "Snapdragon 888",
    screen: 6.2,
    ram: 8,
    colors: [
      { name: "Phantom Gray", hex: "#4f4f53", accent: "#3a3a3d", family: "Gray" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Phantom Violet", hex: "#c9bfd6", accent: "#a79cb8", family: "Purple" },
      { name: "Phantom Pink", hex: "#f0d8d3", accent: "#d8b4ac", family: "Pink" },
    ],
    storage: [
      { gb: 128, price: 259, original: 799, wholesale: 236 },
      { gb: 256, price: 309, original: 849, wholesale: 281 },
    ],
    grade: "good",
    batteryHealth: 86,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 1124,
    stock: 73,
    features: ["Triple camera", "120Hz AMOLED", "Snapdragon 888", "5G"],
    highlights: [
      "Smooth 120Hz Dynamic AMOLED",
      "Versatile triple-camera setup",
      "Compact flagship feel",
    ],
  },
  {
    id: "s21u",
    slug: "galaxy-s21-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S21 Ultra",
    line: "Galaxy S21",
    releaseYear: 2021,
    chip: "Snapdragon 888",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom Silver", hex: "#d9dadc", accent: "#b7b8ba", family: "Silver" },
      { name: "Phantom Titanium", hex: "#6b6c70", accent: "#525357", family: "Gray" },
      { name: "Phantom Navy", hex: "#2f3a4d", accent: "#465570", family: "Blue" },
    ],
    storage: [
      { gb: 128, price: 379, original: 1199, wholesale: 345 },
      { gb: 256, price: 439, original: 1249, wholesale: 400 },
      { gb: 512, price: 509, original: 1379, wholesale: 463 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.6,
    reviews: 1387,
    stock: 49,
    features: ["108MP quad", "100x Space Zoom", "120Hz QHD+", "S Pen support"],
    highlights: [
      "108MP sensor with 100x Space Zoom",
      "Dual telephoto for flexible reach",
      "First S Ultra with S Pen support",
    ],
  },
  {
    id: "s22",
    slug: "galaxy-s22",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S22",
    line: "Galaxy S22",
    releaseYear: 2022,
    chip: "Snapdragon 8 Gen 1",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Pink Gold", hex: "#f1ddd0", accent: "#d9bda9", family: "Pink" },
      { name: "Green", hex: "#bcc6b3", accent: "#98a48d", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 329, original: 799, wholesale: 299 },
      { gb: 256, price: 389, original: 849, wholesale: 354 },
    ],
    grade: "good",
    batteryHealth: 87,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.5,
    reviews: 1056,
    stock: 71,
    features: ["50MP triple", "120Hz AMOLED", "Snapdragon 8 Gen 1", "5G"],
    highlights: [
      "Upgraded 50MP main sensor",
      "Compact body with premium glass",
      "Bright 120Hz adaptive display",
    ],
  },
  {
    id: "s22u",
    slug: "galaxy-s22-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S22 Ultra",
    line: "Galaxy S22",
    releaseYear: 2022,
    chip: "Snapdragon 8 Gen 1",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Phantom White", hex: "#eceae3", accent: "#cac8c1", family: "White" },
      { name: "Green", hex: "#3f4a3c", accent: "#5d6b58", family: "Green" },
      { name: "Burgundy", hex: "#5c2a33", accent: "#7d3a45", family: "Red" },
    ],
    storage: [
      { gb: 128, price: 469, original: 1199, wholesale: 427 },
      { gb: 256, price: 529, original: 1299, wholesale: 481 },
      { gb: 512, price: 609, original: 1399, wholesale: 554 },
    ],
    grade: "excellent",
    batteryHealth: 88,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.7,
    reviews: 1521,
    stock: 45,
    popular: true,
    badge: "S Pen",
    features: ["108MP quad", "Built-in S Pen", "100x Space Zoom", "120Hz QHD+"],
    highlights: [
      "Built-in S Pen returns in Ultra",
      "108MP camera with 100x Space Zoom",
      "Note-style productivity powerhouse",
    ],
  },
  {
    id: "s23",
    slug: "galaxy-s23",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23",
    line: "Galaxy S23",
    releaseYear: 2023,
    chip: "Snapdragon 8 Gen 2",
    screen: 6.1,
    ram: 8,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Green", hex: "#a7b4a0", accent: "#82917a", family: "Green" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 449, original: 799, wholesale: 409 },
      { gb: 256, price: 509, original: 859, wholesale: 463 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.6,
    reviews: 968,
    stock: 64,
    features: ["50MP triple", "Snapdragon 8 Gen 2", "120Hz AMOLED", "5G"],
    highlights: [
      "Efficient Snapdragon 8 Gen 2 for Galaxy",
      "Excellent battery in a compact frame",
      "Refined contour-cut camera design",
    ],
  },
  {
    id: "s23u",
    slug: "galaxy-s23-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S23 Ultra",
    line: "Galaxy S23",
    releaseYear: 2023,
    chip: "Snapdragon 8 Gen 2",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Green", hex: "#3f4a3c", accent: "#5d6b58", family: "Green" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
    ],
    storage: [
      { gb: 256, price: 619, original: 1199, wholesale: 563 },
      { gb: 512, price: 699, original: 1379, wholesale: 636 },
      { gb: 1024, price: 819, original: 1619, wholesale: 745 },
    ],
    grade: "excellent",
    batteryHealth: 91,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.8,
    reviews: 1612,
    stock: 39,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Built-in S Pen", "100x Space Zoom", "120Hz QHD+"],
    highlights: [
      "Massive 200MP main camera sensor",
      "Integrated S Pen for notes and art",
      "Snapdragon 8 Gen 2 with vapor cooling",
    ],
  },
  {
    id: "s24",
    slug: "galaxy-s24",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S24",
    line: "Galaxy S24",
    releaseYear: 2024,
    chip: "Snapdragon 8 Gen 3",
    screen: 6.2,
    ram: 8,
    colors: [
      { name: "Onyx Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Marble Gray", hex: "#9a9b9d", accent: "#7a7b7d", family: "Gray" },
      { name: "Cobalt Violet", hex: "#9a93c7", accent: "#7670a8", family: "Purple" },
      { name: "Amber Yellow", hex: "#e8d39a", accent: "#cdb877", family: "Yellow" },
    ],
    storage: [
      { gb: 128, price: 599, original: 799, wholesale: 545 },
      { gb: 256, price: 659, original: 859, wholesale: 600 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 712,
    stock: 81,
    features: ["50MP triple", "Galaxy AI", "120Hz AMOLED", "Snapdragon 8 Gen 3"],
    highlights: [
      "Galaxy AI features built in",
      "Brighter, flatter 120Hz display",
      "Seven years of OS updates",
    ],
  },
  {
    id: "s24u",
    slug: "galaxy-s24-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S24 Ultra",
    line: "Galaxy S24",
    releaseYear: 2024,
    chip: "Snapdragon 8 Gen 3",
    screen: 6.8,
    ram: 12,
    colors: [
      { name: "Titanium Black", hex: "#3a3a3c", accent: "#535355", family: "Titanium" },
      { name: "Titanium Gray", hex: "#9c9c9e", accent: "#7c7c7e", family: "Titanium" },
      { name: "Titanium Violet", hex: "#b6aec4", accent: "#938aa6", family: "Titanium" },
      { name: "Titanium Yellow", hex: "#e6d8a8", accent: "#cabd86", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 939, original: 1299, wholesale: 854 },
      { gb: 512, price: 1029, original: 1419, wholesale: 936 },
      { gb: 1024, price: 1169, original: 1659, wholesale: 1064 },
    ],
    grade: "pristine",
    batteryHealth: 95,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.8,
    reviews: 1344,
    stock: 36,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Titanium frame", "Built-in S Pen", "Galaxy AI"],
    highlights: [
      "Durable titanium build with flat display",
      "200MP camera and improved zoom AI",
      "Galaxy AI and integrated S Pen",
    ],
  },
  {
    id: "s25u",
    slug: "galaxy-s25-ultra",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy S25 Ultra",
    line: "Galaxy S25",
    releaseYear: 2025,
    chip: "Snapdragon 8 Elite",
    screen: 6.9,
    ram: 12,
    colors: [
      { name: "Titanium Black", hex: "#3a3a3c", accent: "#535355", family: "Titanium" },
      { name: "Titanium Silverblue", hex: "#c4ccd4", accent: "#a0a8b0", family: "Titanium" },
      { name: "Titanium Whitesilver", hex: "#e7e7e4", accent: "#c5c5c2", family: "Titanium" },
      { name: "Titanium Gray", hex: "#8f9092", accent: "#707173", family: "Titanium" },
    ],
    storage: [
      { gb: 256, price: 1049, original: 1299, wholesale: 954 },
      { gb: 512, price: 1149, original: 1419, wholesale: 1046 },
      { gb: 1024, price: 1289, original: 1659, wholesale: 1173 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.9,
    reviews: 421,
    stock: 27,
    popular: true,
    badge: "S Pen",
    features: ["200MP main", "Snapdragon 8 Elite", "Built-in S Pen", "Galaxy AI"],
    highlights: [
      "Snapdragon 8 Elite for Galaxy power",
      "Larger 6.9-inch display, slimmer bezels",
      "Advanced Galaxy AI with built-in S Pen",
    ],
  },
  {
    id: "zflip5",
    slug: "galaxy-z-flip5",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy Z Flip5",
    line: "Galaxy Z Flip",
    releaseYear: 2023,
    chip: "Snapdragon 8 Gen 2",
    screen: 6.7,
    ram: 8,
    colors: [
      { name: "Mint", hex: "#bcd6cb", accent: "#97b4a8", family: "Green" },
      { name: "Graphite", hex: "#3c3d40", accent: "#56575b", family: "Gray" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
      { name: "Lavender", hex: "#cfc6da", accent: "#aaa0bc", family: "Purple" },
    ],
    storage: [
      { gb: 256, price: 549, original: 999, wholesale: 500 },
      { gb: 512, price: 629, original: 1119, wholesale: 572 },
    ],
    grade: "excellent",
    batteryHealth: 89,
    cameraLayout: "dual",
    fiveG: true,
    rating: 4.6,
    reviews: 837,
    stock: 43,
    badge: "Foldable",
    features: ["Flex Window", "Foldable AMOLED", "Snapdragon 8 Gen 2", "5G"],
    highlights: [
      "Large 3.4-inch Flex Window cover screen",
      "Folds to a truly pocketable square",
      "Flagship power in a flip design",
    ],
  },
  {
    id: "zfold5",
    slug: "galaxy-z-fold5",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy Z Fold5",
    line: "Galaxy Z Fold",
    releaseYear: 2023,
    chip: "Snapdragon 8 Gen 2",
    screen: 7.6,
    ram: 12,
    colors: [
      { name: "Phantom Black", hex: "#2a2b2d", accent: "#434446", family: "Black" },
      { name: "Icy Blue", hex: "#c2d2d6", accent: "#9eaeb2", family: "Blue" },
      { name: "Cream", hex: "#ece4d6", accent: "#d3c8b3", family: "White" },
    ],
    storage: [
      { gb: 256, price: 899, original: 1799, wholesale: 818 },
      { gb: 512, price: 999, original: 1919, wholesale: 909 },
      { gb: 1024, price: 1149, original: 2159, wholesale: 1046 },
    ],
    grade: "excellent",
    batteryHealth: 90,
    cameraLayout: "vertical",
    fiveG: true,
    rating: 4.7,
    reviews: 692,
    stock: 29,
    badge: "Foldable",
    features: ['7.6" main display', "S Pen support", "Flex Hinge", "Snapdragon 8 Gen 2"],
    highlights: [
      "Tablet-sized 7.6-inch folding display",
      "Multitasking with Flex Mode and S Pen",
      "Slimmer hinge and lighter body",
    ],
  },
  {
    id: "a54",
    slug: "galaxy-a54-5g",
    brand: "Samsung",
    type: "phone",
    name: "Galaxy A54 5G",
    line: "Galaxy A54",
    releaseYear: 2023,
    chip: "Exynos 1380",
    screen: 6.4,
    ram: 8,
    colors: [
      { name: "Awesome Graphite", hex: "#3a3b3e", accent: "#535458", family: "Black" },
      { name: "Awesome White", hex: "#edece7", accent: "#cbcac5", family: "White" },
      { name: "Awesome Violet", hex: "#b6aec9", accent: "#928aa6", family: "Purple" },
      { name: "Awesome Lime", hex: "#c3cf9f", accent: "#9faa7c", family: "Green" },
    ],
    storage: [
      { gb: 128, price: 269, original: 449, wholesale: 245 },
      { gb: 256, price: 309, original: 499, wholesale: 281 },
    ],
    grade: "good",
    batteryHealth: 90,
    cameraLayout: "grid",
    fiveG: true,
    rating: 4.5,
    reviews: 904,
    stock: 88,
    badge: "Budget pick",
    features: ["50MP triple", "120Hz Super AMOLED", "Exynos 1380", "5G"],
    highlights: [
      "Premium features at a mid-range price",
      "Smooth 120Hz Super AMOLED screen",
      "Large battery for all-day use",
    ],
  },
  {
    id: "ipad9",
    slug: "ipad-9th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (9th gen)",
    line: "iPad",
    releaseYear: 2021,
    chip: "A13 Bionic",
    screen: 10.2,
    ram: 3,
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
    ],
    storage: [
      { gb: 64, price: 199, original: 329, wholesale: 181 },
      { gb: 256, price: 279, original: 479, wholesale: 254 },
    ],
    grade: "good",
    batteryHealth: 93,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 1583,
    stock: 124,
    badge: "Budget pick",
    features: ["A13 Bionic", '10.2" Retina', "Touch ID", "Apple Pencil 1"],
    highlights: [
      "Most affordable way into iPadOS",
      "Reliable A13 for everyday tasks",
      "Works with Apple Pencil and keyboards",
    ],
  },
  {
    id: "ipad10",
    slug: "ipad-10th-gen",
    brand: "Apple",
    type: "tablet",
    name: "iPad (10th gen)",
    line: "iPad",
    releaseYear: 2022,
    chip: "A14 Bionic",
    screen: 10.9,
    ram: 4,
    colors: [
      { name: "Blue", hex: "#7da3b8", accent: "#5c8298", family: "Blue" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink" },
      { name: "Yellow", hex: "#ecd98c", accent: "#cfbb67", family: "Yellow" },
      { name: "Silver", hex: "#e3e4e0", accent: "#c2c3bf", family: "Silver" },
    ],
    storage: [
      { gb: 64, price: 269, original: 449, wholesale: 245 },
      { gb: 256, price: 349, original: 599, wholesale: 318 },
    ],
    grade: "excellent",
    batteryHealth: 94,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.6,
    reviews: 1021,
    stock: 97,
    features: ["A14 Bionic", '10.9" Liquid Retina', "USB-C", "Landscape camera"],
    highlights: [
      "All-screen design in fun colors",
      "Landscape front camera for video calls",
      "USB-C and Apple Pencil support",
    ],
  },
  {
    id: "ipadmini6",
    slug: "ipad-mini-6",
    brand: "Apple",
    type: "tablet",
    name: "iPad mini (6th gen)",
    line: "iPad mini",
    releaseYear: 2021,
    chip: "A15 Bionic",
    screen: 8.3,
    ram: 4,
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink" },
      { name: "Purple", hex: "#c3bcd2", accent: "#9f98b4", family: "Purple" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
    ],
    storage: [
      { gb: 64, price: 319, original: 499, wholesale: 290 },
      { gb: 256, price: 419, original: 649, wholesale: 381 },
    ],
    grade: "excellent",
    batteryHealth: 93,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.7,
    reviews: 868,
    stock: 58,
    features: ["A15 Bionic", '8.3" Liquid Retina', "Touch ID", "Apple Pencil 2"],
    highlights: [
      "Ultra-portable full-power iPad",
      "Edge-to-edge 8.3-inch display",
      "Apple Pencil 2 support with USB-C",
    ],
  },
  {
    id: "ipadair5",
    slug: "ipad-air-5-m1",
    brand: "Apple",
    type: "tablet",
    name: "iPad Air (5th gen, M1)",
    line: "iPad Air",
    releaseYear: 2022,
    chip: "Apple M1",
    screen: 10.9,
    ram: 8,
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#9fc0cf", accent: "#789fb0", family: "Blue" },
      { name: "Purple", hex: "#c8c2dc", accent: "#a39cbe", family: "Purple" },
      { name: "Pink", hex: "#eccdc8", accent: "#d3a8a2", family: "Pink" },
    ],
    storage: [
      { gb: 64, price: 399, original: 599, wholesale: 363 },
      { gb: 256, price: 499, original: 749, wholesale: 454 },
    ],
    grade: "excellent",
    batteryHealth: 95,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.8,
    reviews: 1132,
    stock: 62,
    popular: true,
    badge: "Great value",
    features: ["Apple M1", '10.9" Liquid Retina', "USB-C", "Apple Pencil 2"],
    highlights: [
      "Desktop-class M1 chip in a thin Air",
      "Vivid 10.9-inch Liquid Retina display",
      "Center Stage front camera",
    ],
  },
  {
    id: "ipadair11m2",
    slug: "ipad-air-11-m2",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Air 11" (M2)',
    line: "iPad Air",
    releaseYear: 2024,
    chip: "Apple M2",
    screen: 11,
    ram: 8,
    colors: [
      { name: "Space Gray", hex: "#52555a", accent: "#3c3e42", family: "Gray" },
      { name: "Starlight", hex: "#f3efe6", accent: "#d9d3c4", family: "White" },
      { name: "Blue", hex: "#aebfc9", accent: "#899ba6", family: "Blue" },
      { name: "Purple", hex: "#c4bdd0", accent: "#9f98b2", family: "Purple" },
    ],
    storage: [
      { gb: 128, price: 469, original: 599, wholesale: 427 },
      { gb: 256, price: 549, original: 699, wholesale: 500 },
      { gb: 512, price: 679, original: 899, wholesale: 618 },
    ],
    grade: "pristine",
    batteryHealth: 97,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.8,
    reviews: 564,
    stock: 48,
    features: ["Apple M2", '11" Liquid Retina', "USB-C", "Apple Pencil Pro"],
    highlights: [
      "Powerful M2 chip for creative work",
      "Landscape Center Stage camera",
      "Apple Pencil Pro and Magic Keyboard ready",
    ],
  },
  {
    id: "ipadpro11m4",
    slug: "ipad-pro-11-m4",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 11" (M4)',
    line: "iPad Pro",
    releaseYear: 2024,
    chip: "Apple M4",
    screen: 11,
    ram: 8,
    colors: [
      { name: "Space Black", hex: "#2a2b2e", accent: "#45464a", family: "Black" },
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc1", family: "Silver" },
    ],
    storage: [
      { gb: 256, price: 799, original: 999, wholesale: 727 },
      { gb: 512, price: 949, original: 1199, wholesale: 864 },
      { gb: 1024, price: 1149, original: 1599, wholesale: 1046 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.9,
    reviews: 318,
    stock: 26,
    badge: "Tandem OLED",
    features: ["M4 chip", "Ultra Retina XDR", "Tandem OLED", "Thinnest ever"],
    highlights: [
      "Stunning Tandem OLED Ultra Retina XDR display",
      "M4 chip outpaces most laptops",
      "Incredibly thin and light Pro design",
    ],
  },
  {
    id: "ipadpro13m4",
    slug: "ipad-pro-13-m4",
    brand: "Apple",
    type: "tablet",
    name: 'iPad Pro 13" (M4)',
    line: "iPad Pro",
    releaseYear: 2024,
    chip: "Apple M4",
    screen: 13,
    ram: 8,
    colors: [
      { name: "Space Black", hex: "#2a2b2e", accent: "#45464a", family: "Black" },
      { name: "Silver", hex: "#dcdde0", accent: "#bcbdc1", family: "Silver" },
    ],
    storage: [
      { gb: 256, price: 949, original: 1299, wholesale: 879 },
      { gb: 512, price: 1099, original: 1499, wholesale: 1019 },
    ],
    grade: "pristine",
    batteryHealth: 98,
    cameraLayout: "single",
    fiveG: false,
    cellular: true,
    rating: 4.9,
    reviews: 204,
    stock: 22,
    badge: "Tandem OLED",
    features: ["M4 chip", "Ultra Retina XDR", "Tandem OLED", "Thinnest ever"],
    highlights: [
      "Stunning Tandem OLED Ultra Retina XDR display",
      "M4 chip outpaces most laptops",
      "Thinnest Apple product ever made",
    ],
  },
];

/** Path to the pre-rendered 3D product photo for a device (see /public/renders). */
export function renderSrc(slug: string): string {
  return `/renders/${slug}.png`;
}

export function getDevice(slug: string): Device | undefined {
  return DEVICES.find((d) => d.slug === slug);
}

export function baseStorage(d: Device): StorageOption {
  return d.storage.reduce((a, b) => (b.price < a.price ? b : a), d.storage[0]);
}

export function startingPrice(d: Device): number {
  return Math.min(...d.storage.map((s) => s.price));
}

export function storageFor(d: Device, gb: number): StorageOption {
  return d.storage.find((s) => s.gb === gb) ?? baseStorage(d);
}

export function defaultColor(d: Device): Colorway {
  return d.colors[0];
}

export function bestDiscount(d: Device): number {
  return Math.max(
    ...d.storage.map((s) => (s.original > 0 ? Math.round((1 - s.price / s.original) * 100) : 0)),
  );
}

export function popularDevices(): Device[] {
  return DEVICES.filter((d) => d.popular);
}

export function devicesOfType(type: DeviceType): Device[] {
  return DEVICES.filter((d) => d.type === type);
}

export function relatedDevices(device: Device, count = 4): Device[] {
  return DEVICES.filter((d) => d.id !== device.id)
    .map((d) => {
      let score = 0;
      if (d.type === device.type) score += 2;
      if (d.brand === device.brand) score += 1;
      if (d.line === device.line) score += 2;
      if (Math.abs(startingPrice(d) - startingPrice(device)) < 200) score += 1;
      return { d, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, count)
    .map((x) => x.d);
}

// ---- derived spec strings (grounded in existing fields; no fabricated data) -

const CAMERA_COUNT: Record<CameraLayout, string> = {
  triple: "Triple",
  dual: "Dual",
  single: "Single",
  vertical: "Triple",
  grid: "Quad",
  bar: "Dual",
  circular: "Dual",
};

/** Display panel description, e.g. `6.1" Super Retina XDR OLED`. */
export function displaySpec(d: Device): string {
  const panel =
    d.brand === "Apple"
      ? d.type === "tablet"
        ? "Liquid Retina"
        : "Super Retina XDR OLED"
      : d.type === "tablet"
        ? "Touchscreen LCD"
        : "Dynamic AMOLED";
  return `${d.screen}" ${panel}`;
}

/** Rear-camera summary, reusing the catalog's own feature copy when it names MP. */
export function rearCameraSpec(d: Device): string {
  const mp = d.features.find((f) => /\d\s?MP/i.test(f));
  const count = CAMERA_COUNT[d.cameraLayout] ?? "Multi";
  if (d.type === "tablet") return mp ?? "12MP Wide";
  return mp ? `${count} · ${mp}` : `${count} camera`;
}

/** Front-camera summary. */
export function frontCameraSpec(d: Device): string {
  return d.brand === "Apple" ? "12MP TrueDepth · Face ID" : "Selfie camera";
}

/** Ingress-protection rating, derived from line/type. */
export function waterResistance(d: Device): string {
  if (d.type === "tablet") return "Not rated";
  if (d.line.includes("SE")) return "IP67";
  if (/Galaxy A/.test(d.name)) return "IP67";
  if (/Z Flip|Z Fold/.test(d.name)) return "IPX8";
  return "IP68";
}

/** SIM support. */
export function simType(d: Device): string {
  if (d.type === "tablet") return d.cellular ? "Nano-SIM + eSIM" : "Wi-Fi only";
  return "Nano-SIM + eSIM";
}
